/**
 * src/crystals/db/batch-c9b.data.ts
 * GAIA-OS Crystal Database — Batch C-9B
 *
 * Entries:
 *   1. Cryolite       — sodium aluminium fluoride; near-invisible in water; nearly extinct in nature
 *   2. Cuprite        — copper(I) oxide; one of the deepest reds in mineralogy
 *   3. Cymophane      — cat's eye chrysoberyl; chatoyancy from needle inclusions; H8.5
 *   4. Cyanotrichite  — electric sky-blue acicular copper sulfate; extremely rare; toxic
 *   5. Cyprine        — blue vesuvianite/idocrase; rare copper-bearing blue variety
 *
 * Schema: CrystalRecord v1.3
 * Author: GAIA-OS Crystal Intelligence Engine
 * Date:   2026-05-31
 */

import type { CrystalRecord } from './crystal.schema';

const BATCH_C9B: CrystalRecord[] = [
  {
    name: 'Cryolite',
    mindat_id: 1169,
    rruff_ids: ['R060376'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Obsidian',
    physical: {
      id: 1169,
      longid: 'cryolite',
      guid: '',
      name: 'Cryolite',
      ima_formula: 'Na₃AlF₆',
      mindat_formula: 'Na3AlF6',
      ima_status: 'A',
      ima_year: 1799,
      strunzten: '3.CB.15',
      dana8ed: '11.3.1.1',
      crystal_system: 'Monoclinic',
      hardness_min: 2.5,
      hardness_max: 3,
      specific_gravity_min: 2.95,
      specific_gravity_max: 2.97,
      cleavage: 'None; parting on {001} and {110}',
      fracture: 'Uneven to conchoidal',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Greasy', 'Pearly'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Colourless, snow-white, pale yellow, pale brown, rarely black; becomes nearly invisible when submerged in water due to matching refractive index.',
      streak: 'White',
      fluorescence: 'None',
      ri_min: 1.338,
      ri_max: 1.340,
      birefringence: 0.001,
      optical_type: 'B',
      shortdesc: 'Cryolite — Na₃AlF₆, monoclinic sodium aluminium fluoride. Nearly invisible in water (RI ~1.339, water ~1.333). Once mined exclusively at Ivigtut, Greenland; natural deposit now exhausted. H2.5–3. Fluoride-bearing; avoid water use.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1169.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Cryolite',
      refractive_index: { n_alpha: 1.3385, n_beta: 1.3389, n_gamma: 1.3396 },
      birefringence: 0.001,
      optical_sign: '+',
      dispersion: 'Very low',
      pleochroism: 'None',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra: ['R060376'],
    },
    color: {
      primary_color: 'Colourless to snow-white',
      color_variants: [
        'Pure colourless transparent',
        'Snow-white massive',
        'Pale straw-yellow',
        'Pale brownish matrix material',
      ],
      dominant_wavelength_nm: null,
      oklch: { l: 0.97, c: 0.01, h: 90 },
      hex: '#f8f8f4',
      munsell: 'N 9.5/',
      color_temperature_k: null,
      psychological_effects: [
        'Cryolite is optically almost nothing — it reads as pure absence of colour, a stone that erases itself.',
        'Its near-invisibility in water is one of the most uncanny optical phenomena in mineralogy, creating a sense of dissolving boundaries.',
        'The snow-white massive form reads as pristine, arctic, and still.',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues: null,
        analogous_range: null,
      },
    },
    metaphysical: {
      mineral_name: 'Cryolite',
      chakra_primary: 'Crown',
      chakra_secondary: ['Third Eye', 'Soul Star'],
      element: ['Ice', 'Akasha'],
      planet: ['Neptune', 'Moon'],
      archetype: ['The Invisible Gate', 'The Arctic Mirror'],
      zodiac: ['Pisces', 'Aquarius'],
      numerology: 1,
      angel_number: 111,
      intention: 'I dissolve the boundary between the seen and the unseen.',
      traditions: [
        'Mined almost exclusively from Ivigtut, Greenland — a single deposit now fully exhausted, making natural cryolite one of the rarest minerals on Earth.',
        'Once industrially essential: the entire global aluminium industry was built on cryolite electrolysis before synthetic alternatives were found in 1886.',
        'Its name derives from Greek kryos (frost/ice) + lithos (stone) — the ice stone.',
      ],
      properties: [
        'Nearly invisible in water — its refractive index (1.339) is almost identical to water (1.333), making it essentially disappear when submerged.',
        'Fluoride-bearing mineral; never use in water or elixirs.',
        'Natural specimens are extremely rare collector pieces; all industrial cryolite since 1886 has been synthetic.',
      ],
      gaia_resonance: 'Noosphere + ClarusLens',
      safety_warning: '⚠️ Fluoride-bearing mineral. Do not use in water or elixirs. Avoid prolonged skin contact and wash hands after handling.',
    },
  },
  {
    name: 'Cuprite',
    mindat_id: 1218,
    rruff_ids: ['R060146'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Malachite',
    physical: {
      id: 1218,
      longid: 'cuprite',
      guid: '',
      name: 'Cuprite',
      ima_formula: 'Cu₂O',
      mindat_formula: 'Cu2O',
      ima_status: 'A',
      ima_year: 1845,
      strunzten: '4.AA.10',
      dana8ed: '4.2.1.1',
      crystal_system: 'Cubic',
      hardness_min: 3.5,
      hardness_max: 4,
      specific_gravity_min: 5.85,
      specific_gravity_max: 6.15,
      cleavage: 'Imperfect on {111}',
      fracture: 'Conchoidal to uneven',
      tenacity: 'Brittle to sectile',
      luster: ['Adamantine', 'Submetallic'],
      diaphaneity: ['Transparent', 'Translucent', 'Opaque'],
      colour: 'Deep ruby-red, crimson, brownish-red to almost black in massive form; translucent to transparent in thin crystals with exceptional depth of colour.',
      streak: 'Brownish red',
      fluorescence: 'None',
      ri_min: 2.705,
      ri_max: 2.705,
      birefringence: null,
      optical_type: 'U',
      shortdesc: 'Cuprite — Cu₂O, cubic copper(I) oxide. One of the deepest, most saturated reds in mineralogy — ruby-red to crimson with adamantine lustre. H3.5–4, SG 5.85–6.15. Secondary copper mineral. Toxic; avoid water.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1218.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Cuprite',
      refractive_index: { n_iso: 2.705 },
      birefringence: null,
      optical_sign: null,
      dispersion: 'Strong',
      pleochroism: 'None (isotropic — cubic)',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 620, max: 660 },
      spectra: ['R060146'],
    },
    color: {
      primary_color: 'Deep ruby-red to crimson',
      color_variants: [
        'Ruby-red transparent octahedra',
        'Crimson capillary chalcotrichite variety',
        'Brownish-red massive',
        'Near-black submetallic massive',
      ],
      dominant_wavelength_nm: 640,
      oklch: { l: 0.42, c: 0.22, h: 29 },
      hex: '#8b1a1a',
      munsell: '5R 3/10',
      color_temperature_k: null,
      psychological_effects: [
        'Cuprite carries one of the most saturated reds in the mineral world — a deep, arterial, blood-of-the-Earth red.',
        'Its adamantine lustre in thin crystals produces a jewel-like fire that feels primally alive.',
        'The colour is grounding and activating simultaneously — the red that does not scatter but concentrates.',
      ],
      harmonics: {
        complementary_hue: 209,
        triadic_hues: [149, 269],
        analogous_range: [9, 49],
      },
    },
    metaphysical: {
      mineral_name: 'Cuprite',
      chakra_primary: 'Root',
      chakra_secondary: ['Sacral', 'Earth Star'],
      element: ['Fire', 'Earth'],
      planet: ['Mars', 'Venus'],
      archetype: ['The Blood of the Earth', 'The Deep Red Anchor'],
      zodiac: ['Aries', 'Taurus'],
      numerology: 1,
      angel_number: 111,
      intention: 'I am rooted in the blood of the living Earth.',
      traditions: [
        'Name from Latin cuprum (copper) — one of the primary ores of copper across ancient mining cultures.',
        'Found in iconic copper-mining regions including the Arizona copper belt, Namibia, and Ural Mountains.',
        'The chalcotrichite variety — hair-thin capillary crystal sprays — is among the most visually extraordinary mineral forms in existence.',
      ],
      properties: [
        'Secondary copper oxide mineral from oxidized copper ore zones.',
        'Copper-bearing; avoid water, elixirs, and prolonged skin contact.',
        'Energetically associated with primal life-force, blood, and deep Earth connection.',
      ],
      gaia_resonance: 'AnchorPrism + SovereignCore',
      safety_warning: '⚠️ Copper-bearing mineral. Do not use in water or elixirs. Avoid prolonged skin contact. Wash hands after handling.',
    },
  },
  {
    name: 'Cymophane',
    mindat_id: null,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Black Tourmaline',
    physical: {
      id: null,
      longid: 'cymophane',
      guid: '',
      name: 'Cymophane (Cat\'s Eye Chrysoberyl — trade/varietal name for chatoyant chrysoberyl)',
      ima_formula: 'BeAl₂O₄',
      mindat_formula: 'BeAl2O4',
      ima_status: 'Not IMA approved as separate species — variety of chrysoberyl (IMA 1912)',
      ima_year: null,
      strunzten: '4.BA.05',
      dana8ed: '7.2.1.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 8.5,
      hardness_max: 8.5,
      specific_gravity_min: 3.68,
      specific_gravity_max: 3.78,
      cleavage: 'Distinct on {110}',
      fracture: 'Conchoidal to uneven',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Silky (chatoyant band)'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Honey-yellow, golden-yellow, yellow-green, greenish-yellow; the defining feature is a sharp, bright chatoyant band (the eye) caused by dense parallel needle inclusions.',
      streak: 'White',
      fluorescence: 'None to weak yellowish',
      ri_min: 1.745,
      ri_max: 1.757,
      birefringence: 0.009,
      optical_type: 'B',
      shortdesc: 'Cymophane (Cat\'s Eye Chrysoberyl) — BeAl₂O₄, orthorhombic beryllium aluminium oxide. Honey to golden chatoyant variety of chrysoberyl showing a sharp moving eye band from dense parallel needle inclusions. H8.5. In gemology, "cat\'s eye" unqualified means cymophane.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1008.html',
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: true,
    },
    optical: {
      mineral_name: 'Cymophane',
      refractive_index: { n_alpha: 1.745, n_beta: 1.748, n_gamma: 1.757 },
      birefringence: 0.009,
      optical_sign: '+',
      dispersion: 'Low to moderate',
      pleochroism: 'Weak — yellowish green / yellow / colourless',
      fluorescence_lw: 'None to weak yellow',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 570, max: 590 },
      spectra: [],
    },
    color: {
      primary_color: 'Honey-golden yellow with chatoyant white eye band',
      color_variants: [
        'Honey-yellow',
        'Greenish-yellow',
        'Golden-brown',
        'Pale straw-yellow',
      ],
      dominant_wavelength_nm: 580,
      oklch: { l: 0.80, c: 0.18, h: 88 },
      hex: '#d4a843',
      munsell: '2.5Y 7/10',
      color_temperature_k: null,
      psychological_effects: [
        'The living eye band that moves as the stone is tilted creates an immediate sense of being watched or accompanied.',
        'Its honey-gold colour reads as warm, wise, and quietly alert.',
        'Cymophane is one of the few stones where the optical phenomenon, not the colour, is the defining visual experience.',
      ],
      harmonics: {
        complementary_hue: 268,
        triadic_hues: [208, 328],
        analogous_range: [68, 108],
      },
    },
    metaphysical: {
      mineral_name: 'Cymophane',
      chakra_primary: 'Solar Plexus',
      chakra_secondary: ['Third Eye', 'Crown'],
      element: ['Fire', 'Air'],
      planet: ['Sun', 'Jupiter'],
      archetype: ['The Watchful Eye', 'The Golden Sentinel'],
      zodiac: ['Leo', 'Capricorn'],
      numerology: 9,
      angel_number: 999,
      intention: 'I see clearly through the movement between light and shadow.',
      traditions: [
        'The name cymophane comes from Greek kyma (wave) + phainein (to appear) — the appearing wave, describing the sliding eye band.',
        'In gemology, when a gemmologist says "cat\'s eye" without qualification, they always mean cymophane — no other stone earns the unqualified name.',
        'Sri Lanka (formerly Ceylon) produces the finest specimens; it is the national gemstone in Sri Lankan heritage.',
      ],
      properties: [
        'The chatoyancy (cat\'s eye effect) is caused by dense parallel needles of rutile or other inclusions reflecting a single band of light.',
        'One of the hardest chatoyant stones at H8.5 — durable enough for fine jewelry.',
        'Safe for water and everyday use; beryllium is locked in stable crystal structure.',
      ],
      gaia_resonance: 'ClarusLens + SovereignCore',
      safety_warning: 'Safe for water. Beryllium is locked in stable AlBeO crystal structure; no known hazard from polished stones. Normal jewelry handling.',
    },
  },
  {
    name: 'Cyanotrichite',
    mindat_id: 1228,
    rruff_ids: ['R061016'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Cuprite',
    physical: {
      id: 1228,
      longid: 'cyanotrichite',
      guid: '',
      name: 'Cyanotrichite',
      ima_formula: 'Cu₄Al₂(SO₄)(OH)₁₂·2H₂O',
      mindat_formula: 'Cu4Al2(SO4)(OH)12·2H2O',
      ima_status: 'A',
      ima_year: 1839,
      strunzten: '7.DD.40',
      dana8ed: '31.8.1.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 1,
      hardness_max: 2,
      specific_gravity_min: 2.74,
      specific_gravity_max: 2.95,
      cleavage: 'Perfect on {100}',
      fracture: 'Uneven',
      tenacity: 'Flexible (acicular crystals)',
      luster: ['Silky', 'Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Vivid sky-blue to azure-blue; one of the most intensely coloured blue secondary copper minerals, often forming radiating acicular tufts or velvety blue coatings.',
      streak: 'Pale blue',
      fluorescence: 'None reported',
      ri_min: 1.588,
      ri_max: 1.655,
      birefringence: 0.067,
      optical_type: 'B',
      shortdesc: 'Cyanotrichite — Cu₄Al₂(SO₄)(OH)₁₂·2H₂O, orthorhombic copper aluminium sulfate hydroxide hydrate. Vivid sky-blue acicular tufts and velvety coatings. H1–2, extremely soft. Toxic in water; copper-bearing.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1228.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Cyanotrichite',
      refractive_index: { n_alpha: 1.588, n_beta: 1.617, n_gamma: 1.655 },
      birefringence: 0.067,
      optical_sign: '+',
      dispersion: 'Moderate',
      pleochroism: 'Sky-blue / pale blue / colourless',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 460, max: 490 },
      spectra: ['R061016'],
    },
    color: {
      primary_color: 'Vivid sky-blue to azure',
      color_variants: [
        'Vivid azure acicular tufts',
        'Sky-blue velvety coatings',
        'Deep blue radiating sprays',
        'Pale blue massive',
      ],
      dominant_wavelength_nm: 475,
      oklch: { l: 0.64, c: 0.22, h: 248 },
      hex: '#2a7fc9',
      munsell: '5B 5/12',
      color_temperature_k: null,
      psychological_effects: [
        'Cyanotrichite is one of the most electrically vivid blues in the mineral world — a sky-blue that reads as open, aerial, and immediate.',
        'The acicular tuft form creates a visual sensation of upward movement and expansion.',
        'Its rarity and fragility make it feel precious and irreplaceable, heightening attentiveness.',
      ],
      harmonics: {
        complementary_hue: 68,
        triadic_hues: [8, 128],
        analogous_range: [228, 268],
      },
    },
    metaphysical: {
      mineral_name: 'Cyanotrichite',
      chakra_primary: 'Throat',
      chakra_secondary: ['Third Eye', 'Crown'],
      element: ['Air', 'Water'],
      planet: ['Mercury', 'Uranus'],
      archetype: ['The Sky Tuft', 'The Electric Messenger'],
      zodiac: ['Gemini', 'Aquarius'],
      numerology: 5,
      angel_number: 555,
      intention: 'I carry the message of the open sky in fine blue threads.',
      traditions: [
        'Name from Greek kyanos (blue) + thrix/trich- (hair) — blue hair, perfectly describing its acicular azure tufts.',
        'Known from oxidized copper zones in Romania (classic locality), Arizona, and the Congo.',
        'Rare and fragile; primarily a cabinet specimen admired for colour intensity and crystal habit.',
      ],
      properties: [
        'Extremely soft (H1–2); handle only with care and store protected from moisture and mechanical damage.',
        'Copper-bearing sulfate; never use in water, elixirs, or bodywork.',
        'Yin-yang paired with Cuprite — the deepest red paired with the most vivid blue, copper in two oxidation states.',
      ],
      gaia_resonance: 'ClarusLens + Noosphere',
      safety_warning: '⚠️ Copper-bearing mineral. Extremely soft and fragile. Do not use in water or elixirs. Avoid ingestion and wash hands after handling.',
    },
  },
  {
    name: 'Cyprine',
    mindat_id: null,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Hessonite Garnet',
    physical: {
      id: null,
      longid: 'cyprine',
      guid: '',
      name: 'Cyprine (blue copper-bearing vesuvianite/idocrase — varietal trade name)',
      ima_formula: 'Ca₁₀(Mg,Fe)₂Al₄(SiO₄)₅(Si₂O₇)₂(OH,F)₄ + Cu²⁺ chromophore',
      mindat_formula: 'Complex sorosilicate with Cu substitution',
      ima_status: 'Not IMA approved as separate species — blue Cu-bearing variety of vesuvianite (IMA 1795)',
      ima_year: null,
      strunzten: '9.BG.35',
      dana8ed: '58.2.1.1',
      crystal_system: 'Tetragonal',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 3.32,
      specific_gravity_max: 3.47,
      cleavage: 'Imperfect on {110} and {100}',
      fracture: 'Subconchoidal to uneven',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Resinous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Sky-blue to teal-blue, blue-green; the rare blue colour in vesuvianite is caused by Cu²⁺ substitution — one of the few blue sorosilicates in nature.',
      streak: 'White',
      fluorescence: 'None to weak',
      ri_min: 1.700,
      ri_max: 1.723,
      birefringence: 0.004,
      optical_type: 'U',
      shortdesc: 'Cyprine — blue Cu²⁺-bearing vesuvianite (idocrase), tetragonal complex sorosilicate. Rare sky-blue to teal variety from Telemark, Norway. H6.5–7. One of the rarest blue gemstone varieties. Safe for water.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1240.html',
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: true,
    },
    optical: {
      mineral_name: 'Cyprine',
      refractive_index: { n_e: 1.700, n_o: 1.723 },
      birefringence: 0.004,
      optical_sign: '-',
      dispersion: 'Moderate',
      pleochroism: 'Weak blue / pale blue',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 470, max: 505 },
      spectra: [],
    },
    color: {
      primary_color: 'Sky-blue to teal-blue',
      color_variants: [
        'Sky-blue transparent',
        'Teal-blue',
        'Blue-green',
        'Pale aqua',
      ],
      dominant_wavelength_nm: 488,
      oklch: { l: 0.68, c: 0.16, h: 232 },
      hex: '#3a9ab5',
      munsell: '5B 6/8',
      color_temperature_k: null,
      psychological_effects: [
        'Cyprine\'s blue is quieter and cooler than copper-chromophore blues — a sky-through-water colour that feels both aerial and fluid.',
        'Its rarity creates a sense of preciousness; very few people have held a cyprine.',
        'The teal range bridges blue and green in a way that feels integrative, whole, and naturally balanced.',
      ],
      harmonics: {
        complementary_hue: 52,
        triadic_hues: [112, 352],
        analogous_range: [212, 252],
      },
    },
    metaphysical: {
      mineral_name: 'Cyprine',
      chakra_primary: 'Heart',
      chakra_secondary: ['Throat', 'Higher Heart'],
      element: ['Water', 'Air'],
      planet: ['Venus', 'Neptune'],
      archetype: ['The Blue Idocrase', 'The Rare Integration'],
      zodiac: ['Libra', 'Pisces'],
      numerology: 6,
      angel_number: 666,
      intention: 'I hold the rarest blue — the heart that speaks and the voice that feels.',
      traditions: [
        'Named for its supposed origin in Cyprus (copper-rich island), though the finest specimens come from Telemark, Norway.',
        'Vesuvianite (its parent species) was named for Mt Vesuvius where it was first described in 1795; cyprine is its rarest colour variety.',
        'Almost never seen in mass-market crystal work due to extreme rarity — a stone for dedicated collectors and advanced practitioners.',
      ],
      properties: [
        'One of the rarest blue gemstone varieties in nature; Cu²⁺ substitution in a sorosilicate host is uncommon.',
        'Safe for water due to copper locked in stable silicate structure.',
        'Heart-Throat integrator — the stone of speaking what the heart truly means.',
      ],
      gaia_resonance: 'ViriditasHeart + ClarusLens',
      safety_warning: 'Safe for water. Copper is locked in stable silicate crystal structure. Normal handling and jewelry use.',
    },
  },
];

export default BATCH_C9B;
