/**
 * batch-a6.data.ts
 * BATCH A-6 | Anhydrite · Angelite · Angel Wing Calcite · Apache Gold · Apache Tear
 * Added: 2026-05-29
 *
 * ⚠️  INTERPRETIVE / TRADITIONAL LAYER — NOT SCIENTIFIC DATA
 * Physics and mineral data sourced from IMA / Mindat / Webmineral conventions.
 * Metaphysical data sourced from established cross-cultural traditions.
 * All records conform to CrystalRecord nested schema.
 *
 * KEY NOTES FOR THIS BATCH:
 * - Anhydrite and Angelite share the same IMA mineral (CaSO₄); Angelite is a
 *   trade name for blue nodular anhydrite from Peru specifically.
 * - Angelite and Anhydrite are WATER-UNSAFE — contact destroys the blue colour
 *   by converting to gypsum.
 * - Apache Gold is a trade name for chalcopyrite-in-chlorite-schist from Jerome AZ.
 * - Apache Tear is obsidian (volcanic glass) — appears black, transmits warm amber
 *   light when held up. A yin-yang pair with Angelite.
 * - Angel Wing Calcite: physically fragile, altar/display only.
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A6: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // ANHYDRITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Anhydrite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Anhydrite',
      ima_formula:     'CaSO₄',
      mindat_formula:  'CaSO4',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '7.AD.30',
      dana8ed:         null,
      crystal_system:  'Orthorhombic',
      hardness_min:    3.0,
      hardness_max:    3.5,
      specific_gravity_min: 2.89,
      specific_gravity_max: 2.98,
      cleavage:        'Perfect {010}, {100}, {001} — three directions at 90°',
      fracture:        'Uneven to splintery',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Pearly', 'Greasy'],
      diaphaneity:     ['Transparent', 'Translucent', 'Opaque'],
      colour:          'Colorless, white, grey, pale blue, pale violet, pink; colour from trace Fe²⁺ or Mn',
      streak:          'White',
      fluorescence:    'Weak pink-orange under LW UV (some specimens)',
      ri_min:          1.567,
      ri_max:          1.614,
      birefringence:   0.044,
      optical_type:    'B',
      shortdesc:       'Anhydrous calcium sulfate — literally named "without water" (Greek: anhydros). IMA-approved. Isostructural with α-BaSO₄ and α-SrSO₄. Readily absorbs water and converts to gypsum (CaSO₄·2H₂O), expanding up to 60% in volume. Perfect 3-directional cleavage at 90°. Vitreous to pearly luster. Forms in evaporite sequences alongside gypsum, halite, and sylvite. Paragenetically precedes Angelite (blue nodular variety).',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-234.html',
      piezoelectric:   false,
      safe_for_water:  false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Anhydrite',
      refractive_index: { n_alpha: 1.567, n_beta: 1.575, n_gamma: 1.614 },
      birefringence:    0.044,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      'Weak to none',
      fluorescence_lw:  'Weak pink-orange (some specimens)',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 440, max: 480 },
      spectra:          [],
    },

    color: {
      primary_color:          'White to pale blue-grey',
      color_variants:         ['Colorless/white (pure)', 'Pale blue-grey', 'Pale violet', 'Pink (Mn-bearing)', 'Grey'],
      dominant_wavelength_nm: 460,
      oklch:                  { l: 0.85, c: 0.04, h: 250 },
      hex:                    '#d8dde8',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'White and cool — neutral clarity, the blank state before information is written',
        'Pale blue-grey: quiet, atmospheric, pre-dawn light',
        'Subtle enough to be a carrier: amplifies without imposing',
        'Precursor energy — the state before transformation into Angelite',
      ],
      harmonics: {
        complementary_hue: 70,
        triadic_hues:      [10, 130],
        analogous_range:   [230, 270],
      },
    },

    metaphysical: {
      mineral_name:     'Anhydrite',
      chakra_primary:   'Throat',
      chakra_secondary: ['Third Eye', 'Crown'],
      element:          ['Air', 'Water'],
      planet:           ['Mercury', 'Neptune'],
      archetype:        ['Messenger', 'Sage'],
      zodiac:           ['Gemini', 'Aquarius', 'Pisces'],
      numerology:       3,
      intention:        'Pure communication — truth spoken clearly before it crystallises into fixed form',
      traditions:       ['Modern Crystal Healing', 'Western Esotericism'],
      properties: [
        'The precursor mineral to Angelite — Angelite IS anhydrite, blue and nodular from Peru',
        'Named "without water" — the dry, clear state before emotion enters the field',
        'Carries the same properties as Angelite in its raw IMA form, but without the colour specificity',
        'Supports clear, neutral communication — stating facts before feelings',
        'Excellent for meditation environments — quiet, amplifying, non-imposing',
        'Dissolves psychic noise; creates a clean signal channel',
        'Absorbs water energetically as well as physically — draws in what is needed, transforms it',
        'The elemental principle: what is dry becomes gypsum when it meets water — transformation through contact',
      ],
      gaia_resonance:   'SomnusVeil + ClarusLens — signal clarity, psychic noise reduction, pre-form communication',
      safety_warning:   'Water-unsafe: absorbs moisture and converts to gypsum, swelling up to 60% in volume. Never in water elixirs. Store away from high humidity. Soft (3–3.5 Mohs) — do not store with harder stones without padding.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANGELITE (Blue Anhydrite — Peru)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Angelite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: 'Apache Tear',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Angelite',
      ima_formula:     'CaSO₄',
      mindat_formula:  'CaSO4',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '7.AD.30',
      dana8ed:         null,
      crystal_system:  'Orthorhombic',
      hardness_min:    3.0,
      hardness_max:    3.5,
      specific_gravity_min: 2.89,
      specific_gravity_max: 2.98,
      cleavage:        'Perfect {010}, {100}, {001}',
      fracture:        'Uneven to splintery',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Pearly'],
      diaphaneity:     ['Translucent', 'Opaque'],
      colour:          'Distinctive pale periwinkle-blue from trace Fe²⁺ substitution; develops white gypsum rind on surface upon water contact — the blue colour is physically destroyed by moisture',
      streak:          'White',
      fluorescence:    'Weak pink-orange under LW UV',
      ri_min:          1.567,
      ri_max:          1.614,
      birefringence:   0.044,
      optical_type:    'B',
      shortdesc:       'Trade name for blue nodular anhydrite (CaSO₄) found specifically in Peru (first discovered 1987). Not an IMA-approved mineral name. Blue colour caused by trace Fe²⁺ substitution. The blue is physically fragile — water contact triggers conversion to gypsum, destroying the colour. One of the most water-sensitive stones in the crystal world.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-234.html',
      piezoelectric:   false,
      safe_for_water:  false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Angelite',
      refractive_index: { n_alpha: 1.567, n_beta: 1.575, n_gamma: 1.614 },
      birefringence:    0.044,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      'Very weak',
      fluorescence_lw:  'Weak pink-orange',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 450, max: 475 },
      spectra:          [],
    },

    color: {
      primary_color:          'Pale periwinkle-blue (unique to Peruvian nodular anhydrite)',
      color_variants:         ['Pale blue', 'Blue-white', 'White (gypsum rind on water-damaged surfaces)'],
      dominant_wavelength_nm: 462,
      oklch:                  { l: 0.72, c: 0.10, h: 255 },
      hex:                    '#a8b8d8',
      munsell:                '7.5PB 7/4',
      color_temperature_k:    null,
      psychological_effects:  [
        'The most delicate blue in the database — softest possible sky, just before dawn',
        'Periwinkle sits between blue and violet: the liminal space between intellect and intuition',
        'Fragility IS the message: this colour cannot survive contact with the physical world unchanged',
        'Calming to an almost sedative degree — quiets mental noise instantly',
        'Yin-yang pair with Apache Tear: maximum softness ↔ maximum volcanic darkness',
      ],
      harmonics: {
        complementary_hue: 75,
        triadic_hues:      [15, 135],
        analogous_range:   [235, 275],
      },
    },

    metaphysical: {
      mineral_name:     'Angelite',
      chakra_primary:   'Throat',
      chakra_secondary: ['Third Eye', 'Crown'],
      element:          ['Air', 'Aether'],
      planet:           ['Neptune', 'Uranus', 'Moon'],
      archetype:        ['Angel', 'Oracle', 'Healer'],
      zodiac:           ['Aquarius', 'Pisces', 'Libra'],
      numerology:       7,
      intention:        'Angelic connection — peace, compassionate truth, bridge to higher realms',
      traditions:       [
        'Modern Crystal Healing (discovered 1987 in Peru)',
        'New Age / Angelology tradition',
        'Western Esotericism',
      ],
      properties: [
        'First discovered 1987 in Peru — one of the newer stones in the crystal healing canon',
        'Said to enhance communication with angels, guides, and higher-dimensional presences',
        'Extremely calming — reduces anxiety, panic, and psychic overwhelm',
        'Supports compassionate truth-telling: speaking difficult things with love',
        'Facilitates out-of-body experiences and lucid dreaming',
        'Useful for grief processing — angelic comfort, not avoidance',
        'Yin-yang pair with Apache Tear: together they hold the full spectrum from softest peace to volcanic darkness',
        'Place near the throat while sleeping to enhance dream communication with guides',
        'The fragility of its colour is a teaching: some states of consciousness are as delicate as this blue',
      ],
      gaia_resonance:   'ClarusLens + SomnusVeil — angelic signal reception, dream bridge, compassionate communication',
      safety_warning:   '⚠️ CRITICAL WATER WARNING: Angelite MUST NEVER contact water. Water converts the blue anhydrite surface to white gypsum, permanently destroying the colour and surface integrity. No water elixirs, no rinsing, no humid storage. Cleanse energetically only (moonlight, sound, smoke). Soft (3–3.5 Mohs) — handle gently.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ANGEL WING CALCITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Angel Wing Calcite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Angel Wing Calcite',
      ima_formula:     'CaCO₃',
      mindat_formula:  'CaCO3',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '5.AB.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    3.0,
      hardness_max:    3.0,
      specific_gravity_min: 2.71,
      specific_gravity_max: 2.71,
      cleavage:        'Perfect rhombohedral {1011} in three directions',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Pearly'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'White to ivory; blade-like crystals with feathered edges catch light with a gold-bronze iridescence at crystal margins',
      streak:          'White',
      fluorescence:    'Strong pink to red under LW UV (typical calcite response)',
      ri_min:          1.486,
      ri_max:          1.658,
      birefringence:   0.172,
      optical_type:    'U',
      shortdesc:       'Trade name for a rare bladed calcite variety from Mexico, forming fan-shaped or wing-shaped crystal clusters with feather-like encrustation on the blade edges. IMA mineral: calcite (CaCO₃). Polymorph with aragonite and vaterite. Extremely high birefringence (0.172) produces the double-image effect visible through Iceland spar. Physically fragile — altar/display only, not for regular handling.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-859.html',
      piezoelectric:   false,
      safe_for_water:  true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Angel Wing Calcite',
      refractive_index: { n_omega: 1.658, n_epsilon: 1.486 },
      birefringence:    0.172,
      optical_sign:     '-',
      dispersion:       'Weak (0.011)',
      pleochroism:      'None (uniaxial)',
      fluorescence_lw:  'Strong pink-red (typical calcite)',
      fluorescence_sw:  'Moderate white-pink',
      phosphorescence:  'Weak short-duration pink',
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'White to ivory with gold-bronze edge iridescence',
      color_variants:         ['Pure white', 'Ivory-warm white', 'Cream with gold crystal edges'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.92, c: 0.04, h: 80 },
      hex:                    '#f5f0e8',
      munsell:                'N 9/',
      color_temperature_k:    5500,
      psychological_effects:  [
        'Purest white in the database — the white of clean light, not absence',
        'Gold edges at crystal margins: the sacred illuminated manuscript quality',
        'Wing shape is literally angelic — the form itself communicates the energy',
        'Extremely high vibration transmitted visually: looking at it induces calm',
        'The feathered crystal edges catch light like a real feather — kinetic sacred geometry',
      ],
      harmonics: {
        complementary_hue: 260,
        triadic_hues:      [200, 320],
        analogous_range:   [60, 100],
      },
    },

    metaphysical: {
      mineral_name:     'Angel Wing Calcite',
      chakra_primary:   'Crown',
      chakra_secondary: ['Higher Crown', 'Soul Star', 'Third Eye'],
      element:          ['Aether', 'Air'],
      planet:           ['Moon', 'Venus', 'Neptune'],
      archetype:        ['Seraph', 'Healer', 'Oracle'],
      zodiac:           ['Libra', 'Pisces', 'Cancer'],
      numerology:       9,
      intention:        'Highest-vibration calcite — direct angelic attunement, crown activation, divine light embodied in form',
      traditions:       [
        'Modern Crystal Healing',
        'Angelic tradition (cross-cultural)',
        'Mexican mineral tradition',
      ],
      properties: [
        'Rarest calcite habit — only found in select Mexican deposits; wing-fan formation is genuinely unusual',
        'Said to be the highest vibrational calcite available',
        'Wing form embodies the literal image of the angelic — sacred geometry made mineral',
        'Activates both hemispheres of the brain simultaneously through the Crown chakra',
        'Facilitates channeling, mediumship, and lucid communication with guides',
        'Teaches discernment — distinguishing angelic guidance from projection or wishful thinking',
        'Calms the mind at the deepest level; excellent for those with racing thoughts',
        'Enhances psychic ability and clairvoyance through the Third Eye',
        'Physically fragile: treat as an altar object. The fragility is part of its teaching — the highest things are precious and must be handled with care',
      ],
      gaia_resonance:   'ClarusLens + Noosphere + SomnusVeil — highest Crown activation, angelic signal clarity, lucid dream facilitation',
      safety_warning:   'Physically fragile — wing-shaped clusters break easily. Use as altar/display only; not for regular handling or pocket stones. Otherwise non-toxic, safe.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // APACHE GOLD
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Apache Gold',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: null,

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Apache Gold',
      ima_formula:     'CuFeS₂ (chalcopyrite) in chlorite schist matrix',
      mindat_formula:  'CuFeS2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '2.CB.10',
      dana8ed:         null,
      crystal_system:  'Amorphous',
      hardness_min:    3.5,
      hardness_max:    6.0,
      specific_gravity_min: 4.1,
      specific_gravity_max: 4.3,
      cleavage:        'None to indistinct (matrix composite)',
      fracture:        'Uneven',
      tenacity:        'Brittle',
      luster:          ['Metallic', 'Sub-Metallic'],
      diaphaneity:     ['Opaque'],
      colour:          'Deep black chlorite schist matrix with vivid metallic brass-gold chalcopyrite inclusions; chalcopyrite frequently shows iridescent peacock tarnish (blue, purple, gold, green)',
      streak:          'Greenish-black (chalcopyrite) on black (schist)',
      fluorescence:    'None',
      ri_min:          null,
      ri_max:          null,
      birefringence:   null,
      optical_type:    null,
      shortdesc:       'Trade name for chalcopyrite (CuFeS₂) in chlorite schist matrix, found exclusively at the United Verde Mine, Jerome, Arizona, USA. Copper-iron sulfide (chalcopyrite) embedded in metamorphic green-black chlorite schist. Chalcopyrite is electrically conductive and mildly piezoelectric. Maximum visual contrast: absolute black matrix, warm metallic gold inclusions. Heavy, dense, grounding.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-952.html',
      piezoelectric:   true,
      safe_for_water:  false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Apache Gold',
      refractive_index: {},
      birefringence:    null,
      optical_sign:     null,
      dispersion:       null,
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 570, max: 600 },
      spectra:          [],
    },

    color: {
      primary_color:          'Deep black with brass-gold metallic inclusions',
      color_variants:         ['Black-gold (classic)', 'Iridescent peacock (blue-purple-gold tarnish on chalcopyrite)', 'Green-black with gold (chlorite-heavy)'],
      dominant_wavelength_nm: 585,
      oklch:                  { l: 0.25, c: 0.18, h: 85 },
      hex:                    '#3a2e08',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Maximum polarity contrast in the database: absolute darkness + pure solar gold',
        'Primal solar power grounded in the Earth — gold not in sky but in stone',
        'Copper-gold: the alchemist\'s palette — transformation from base to precious',
        'Weighted, heavy, grounding — visually communicates density and staying power',
        'No other stone in the DB has this black/gold binary with metallic luster',
      ],
      harmonics: {
        complementary_hue: 265,
        triadic_hues:      [205, 325],
        analogous_range:   [65, 105],
      },
    },

    metaphysical: {
      mineral_name:     'Apache Gold',
      chakra_primary:   'Solar Plexus',
      chakra_secondary: ['Root', 'Sacral'],
      element:          ['Fire', 'Earth'],
      planet:           ['Sun', 'Mars', 'Earth'],
      archetype:        ['Alchemist', 'Warrior', 'Sovereign'],
      zodiac:           ['Leo', 'Aries', 'Capricorn'],
      numerology:       1,
      intention:        'Solar grounding — personal power, confidence, and vitality rooted in the physical world',
      traditions:       [
        'Apache / Southwest Indigenous tradition (Jerome, Arizona — Apache territory)',
        'Alchemical tradition (copper-gold combination)',
        'Modern Crystal Healing',
      ],
      properties: [
        'Found only at the United Verde Mine in Jerome, Arizona — site of ancient and modern copper mining in Apache territory',
        'Chalcopyrite component is mildly piezoelectric — generates a charge under mechanical stress',
        'Grounded solar energy — the gold of the Earth, not the sky; power that is earned and embodied',
        'Inspires confidence, optimism, and decisive action without arrogance',
        'Copper component supports energetic circulation: moves stagnant energy through the body',
        'Strong manifestation stone — aligns will and action, solar plexus to root',
        'The alchemical stone par excellence: black base material + gold inclusion = lead to gold metaphor made literal',
        'Protective and energising simultaneously; good for those who feel drained or disempowered',
        'Heavy density is intentional — the weight is the medicine. Grounds scattered energy fast.',
      ],
      gaia_resonance:   'SovereignCore + QuantumNexus — grounded solar power, piezoelectric node candidate, alchemical manifestation',
      safety_warning:   '⚠️ Chalcopyrite contains copper and iron sulfide. No water elixirs — copper leaches. Do not use near sensitive electronic hardware (mildly piezoelectric — generates charge). Wash hands after extended handling. No ingestion.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // APACHE TEAR (Rhyolitic Obsidian Nodule)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Apache Tear',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: null,
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: 'Angelite',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Apache Tear',
      ima_formula:     'SiO₂ (amorphous volcanic glass)',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.10',
      dana8ed:         null,
      crystal_system:  'Amorphous',
      hardness_min:    5.0,
      hardness_max:    5.5,
      specific_gravity_min: 2.30,
      specific_gravity_max: 2.40,
      cleavage:        'None (amorphous glass)',
      fracture:        'Conchoidal — extremely sharp edges',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Resinous'],
      diaphaneity:     ['Translucent (against light)', 'Opaque (in hand)'],
      colour:          'Jet black in hand; warm mahogany-amber to orange-brown when held to light — two completely different colour identities depending on light transmission vs. reflection',
      streak:          'White',
      fluorescence:    'None',
      ri_min:          1.48,
      ri_max:          1.51,
      birefringence:   null,
      optical_type:    null,
      shortdesc:       'Trade name for small rounded nodules of rhyolitic volcanic glass (obsidian variety) found in perlite deposits. Also called Marekanite. Forms in lava domes and ash-flow tuffs. Appears completely black in reflected light but transmits warm amber-brown light when held to a source — two entirely different colour identities. Conchoidal fracture produces extremely sharp edges. Non-toxic, safe for water.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-2998.html',
      piezoelectric:   false,
      safe_for_water:  true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Apache Tear',
      refractive_index: { n: 1.495 },
      birefringence:    null,
      optical_sign:     null,
      dispersion:       null,
      pleochroism:      null,
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Jet black (reflected) / Warm mahogany-amber (transmitted)',
      color_variants:         ['Jet black (in hand)', 'Warm amber-brown (backlighting)', 'Mahogany (mixed light)', 'Near-opaque dark brown'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.10, c: 0.03, h: 30 },
      hex:                    '#1a1008',
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Dual identity: the opacity of protection, the warmth of amber when light passes through',
        'Black = protection, boundary, containment; Amber = ancient warmth, preserved life, grief transmuted',
        'Holding it against light is a meditation — what appears dark in ordinary conditions reveals warmth under illumination',
        'Yin-yang pair with Angelite: maximum volcanic darkness ↔ maximum sky softness',
        'The gentlest obsidian — rounded, tumbled by the Earth itself; no sharp edges in the hand',
      ],
      harmonics: {
        complementary_hue: 210,
        triadic_hues:      [150, 270],
        analogous_range:   [10, 50],
      },
    },

    metaphysical: {
      mineral_name:     'Apache Tear',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star', 'Heart'],
      element:          ['Earth', 'Fire'],
      planet:           ['Saturn', 'Pluto', 'Mars'],
      archetype:        ['Griever', 'Healer', 'Ancestor'],
      zodiac:           ['Scorpio', 'Aries', 'Capricorn'],
      numerology:       4,
      intention:        'Grief transformed — releasing sorrow with grace, gentle protection, past-life healing',
      traditions:       [
        'Apache Nation tradition (Arizona / New Mexico / Texas)',
        'Legend: Apache women wept for warriors lost to the US cavalry — their tears became these stones',
        'Native American healing tradition',
        'Modern Crystal Healing',
      ],
      properties: [
        'The gentlest protective obsidian — rounded by the Earth, not sharp or aggressive like raw obsidian',
        'Named from the legend of Apache warrior women whose grief turned to stone — carries that emotional depth',
        'Primary stone for grief processing, loss, bereavement, and emotional release',
        'Protects the aura without the intensity of Black Obsidian — appropriate for sensitive people',
        'Grounding without heaviness — the warmth in the amber centre softens the protection',
        'Past-life healing: accesses karmic grief and ancestral sorrow stored in the cellular memory',
        'Excellent for anyone rebuilding after loss — keeps the field sealed and safe while healing happens',
        'Holds against light: the amber warmth is the teaching — what seems like pure darkness always has warmth at the centre',
        'Yin-yang pair with Angelite: one is volcanic darkness, one is sky softness. Together they hold the full emotional range.',
      ],
      gaia_resonance:   'AnchorPrism + ViriditasHeart — gentle grounding, grief transmutation, protected emotional processing',
      safety_warning:   'Conchoidal fracture creates very sharp edges on broken surfaces. Handle raw or broken specimens carefully. Polished/tumbled specimens safe. Non-toxic. Safe for water (indirect elixirs fine). No known hazards.',
    },
  },

];

export default BATCH_A6;
