/**
 * src/crystals/db/batch-b1.data.ts
 * GAIA-OS Crystal Database — Batch B-1
 *
 * Entries:
 *   1. Banded Calcite
 *   2. Baryte
 *   3. Benitoite
 *   4. Beryl
 *   5. Bismuth
 *
 * Schema: CrystalRecord v1.3
 * Author: GAIA-OS Crystal Intelligence Engine
 * Date:   2026-05-29
 */

import type { CrystalRecord } from './crystal.schema';

const BATCH_B1: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // 1. BANDED CALCITE
  // Trade name for layered calcite — alabaster-white with warm honey bands
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Banded Calcite',
    mindat_id:   null,
    rruff_ids:   [],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  true,
    color_layer: 'natural',
    yin_yang_pair: 'Obsidian',

    physical: {
      id:           0,
      longid:       'banded-calcite',
      guid:         '',
      name:         'Calcite (banded variety)',
      ima_formula:  'CaCO₃',
      mindat_formula: 'CaCO3',
      ima_status:   'A',
      ima_year:     null,
      strunzten:    '5.AB.05',
      dana8ed:      '14a.1.1.1',
      crystal_system: 'Trigonal',
      hardness_min: 3,
      hardness_max: 3,
      specific_gravity_min: 2.69,
      specific_gravity_max: 2.71,
      cleavage:    'Perfect rhombohedral on {10Ġ14}',
      fracture:    'Conchoidal',
      tenacity:    'Brittle',
      luster:      ['Vitreous', 'Waxy', 'Resinous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour:      'White, cream, honey, orange-brown — layered in alternating bands',
      streak:      'White',
      fluorescence: 'Strong pink to orange under LW UV',
      ri_min:      1.486,
      ri_max:      1.658,
      birefringence: 0.172,
      optical_type: 'U',
      shortdesc:   'Trade name for layered/banded calcite formed by slow sedimentary or hydrothermal deposition. Exhibits distinct alternating white and honey-amber bands.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-859.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Banded Calcite',
      refractive_index: { n_omega: 1.658, n_epsilon: 1.486 },
      birefringence:   0.172,
      optical_sign:    '-',
      dispersion:      null,
      pleochroism:     null,
      fluorescence_lw: 'Strong pink to orange',
      fluorescence_sw: 'Weak',
      phosphorescence: null,
      visible_wavelength_nm: { min: 580, max: 620 },
      spectra: [],
    },

    color: {
      primary_color:          'Layered cream-white and honey-amber',
      color_variants:         ['Pure white', 'Cream', 'Honey yellow', 'Amber brown', 'Peach'],
      dominant_wavelength_nm: 595,
      oklch:   { l: 0.88, c: 0.06, h: 85 },
      hex:     '#f5e8c4',
      munsell: '2.5Y 9/2',
      color_temperature_k:    3800,
      psychological_effects:  [
        'Deeply soothing — the banding creates visual rhythm that calms the mind',
        'Warm neutrality — neither stimulating nor sedating, simply stabilising',
        'The honey tones evoke nourishment, warmth, and gentle ancestral comfort',
        'Layered visual structure mirrors the layering of time and memory',
      ],
      harmonics: {
        complementary_hue: 265,
        triadic_hues:      [205, 325],
        analogous_range:   [65, 105],
      },
    },

    metaphysical: {
      mineral_name:     'Banded Calcite',
      chakra_primary:   'Crown',
      chakra_secondary: ['Solar Plexus', 'Sacral'],
      element:   ['Earth', 'Water'],
      planet:    ['Moon', 'Venus'],
      archetype: ['The Keeper of Layers', 'The Gentle Ancestor'],
      zodiac:    ['Cancer', 'Taurus'],
      numerology: 4,
      angel_number: 222,
      intention: 'I receive the wisdom held in every layer of my being.',
      traditions: ['Western crystal healing', 'Colour therapy', 'Shamanic traditions'],
      properties: [
        'The banding encodes geological time — each layer a chapter of Earth memory',
        'Deeply calming and emotionally stabilising — excellent for anxiety and overwhelm',
        'Amplifies energy gently then returns it in balanced form — unlike Selenite which amplifies strongly',
        'Supports meditation, inner child healing, and recovery from emotional exhaustion',
        'Often used in massage and energy healing due to its smooth, cool touch',
        'Strong fluorescence under UV is a visual metaphor for its hidden inner light',
      ],
      gaia_resonance: 'SomnusVeil + ViriditasHeart',
      safety_warning: 'Calcite is water-soluble over time — do not use for water elixirs or leave submerged.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. BARYTE (BARITE)
  // Barium sulphate — heavy, white to colourless — the anchor mineral
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Baryte',
    mindat_id:   536,
    rruff_ids:   ['R040078', 'R050128'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Moldavite',

    physical: {
      id:           536,
      longid:       'baryte',
      guid:         '',
      name:         'Baryte',
      ima_formula:  'BaSO₄',
      mindat_formula: 'BaSO4',
      ima_status:   'A',
      ima_year:     1800,
      strunzten:    '7.AD.35',
      dana8ed:      '28.3.1.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 3,
      hardness_max: 3.5,
      specific_gravity_min: 4.3,
      specific_gravity_max: 4.6,
      cleavage:    'Perfect on {001}, good on {210}',
      fracture:    'Uneven',
      tenacity:    'Brittle',
      luster:      ['Vitreous', 'Resinous', 'Pearly'],
      diaphaneity: ['Transparent', 'Translucent', 'Opaque'],
      colour:      'Colourless, white, grey, blue, yellow, brown',
      streak:      'White',
      fluorescence: 'Cream to yellow under LW UV; phosphorescent',
      ri_min:      1.636,
      ri_max:      1.648,
      birefringence: 0.012,
      optical_type: 'B',
      shortdesc:   'Dense barium sulphate — remarkably heavy for a non-metallic mineral. Forms tabular crystals and desert roses. Major industrial mineral.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-536.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Baryte',
      refractive_index: { n_alpha: 1.636, n_beta: 1.637, n_gamma: 1.648 },
      birefringence:   0.012,
      optical_sign:    '+',
      dispersion:      'Weak',
      pleochroism:     null,
      fluorescence_lw: 'Cream to yellow',
      fluorescence_sw: 'Weak cream',
      phosphorescence: 'Yes — cream to yellow',
      visible_wavelength_nm: null,
      spectra: ['R040078', 'R050128'],
    },

    color: {
      primary_color:          'White to colourless',
      color_variants:         ['Pure white', 'Colourless', 'Pale blue', 'Honey yellow', 'Grey'],
      dominant_wavelength_nm: null,
      oklch:   { l: 0.95, c: 0.01, h: 90 },
      hex:     '#f8f6f0',
      munsell: 'N9/',
      color_temperature_k:    6500,
      psychological_effects:  [
        'Pristine clarity — the visual weight of white combined with extreme physical density',
        'Creates paradox: looks light, feels impossibly heavy — mirrors hidden substance',
        'Neutral, non-intrusive — does not impose a colour frequency, only weight and presence',
        'Encourages honest reckoning with what is truly substantial versus what merely appears so',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    metaphysical: {
      mineral_name:     'Baryte',
      chakra_primary:   'Root',
      chakra_secondary: ['Crown'],
      element:   ['Earth'],
      planet:    ['Saturn'],
      archetype: ['The Anchor', 'The Weighmaster'],
      zodiac:    ['Aquarius', 'Capricorn'],
      numerology: 1,
      angel_number: 444,
      intention: 'I am fully present, fully grounded, fully here.',
      traditions: ['Western crystal healing', 'Shamanic earth-anchor work'],
      properties: [
        'The heaviest common non-metallic mineral — its weight IS its medicine',
        'Profound grounding — brings scattered energy back to Earth with extraordinary force',
        'Bridges Root and Crown — keeps spiritual experiences tethered to the body',
        'Desert Rose form (baryte rosettes) widely used in spiritual practices',
        'Assists in dream recall without losing grounding upon waking',
        'Barium content makes this toxic if powdered or ingested — display only',
      ],
      gaia_resonance: 'AnchorPrism + SomnusVeil',
      safety_warning: 'Contains barium — TOXIC if ingested or inhaled as dust. Never use for water elixirs. Safe for display and holding. Do not sand or polish without respiratory protection.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. BENITOITE
  // Barium titanium cyclosilicate — California’s state gem — rarest blue
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Benitoite',
    mindat_id:   661,
    rruff_ids:   ['R040052', 'R050335'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Sunstone',

    physical: {
      id:           661,
      longid:       'benitoite',
      guid:         '',
      name:         'Benitoite',
      ima_formula:  'BaTiSi₃O₉',
      mindat_formula: 'BaTiSi3O9',
      ima_status:   'A',
      ima_year:     1907,
      strunzten:    '9.CA.05',
      dana8ed:      '60.1.1.1',
      crystal_system: 'Hexagonal',
      hardness_min: 6,
      hardness_max: 6.5,
      specific_gravity_min: 3.64,
      specific_gravity_max: 3.68,
      cleavage:    'Poor/indistinct',
      fracture:    'Conchoidal',
      tenacity:    'Brittle',
      luster:      ['Vitreous'],
      diaphaneity: ['Transparent'],
      colour:      'Sapphire blue to colourless',
      streak:      'White',
      fluorescence: 'Strong blue-white under SW UV — one of the most spectacular fluorescences known',
      ri_min:      1.756,
      ri_max:      1.804,
      birefringence: 0.048,
      optical_type: 'U',
      shortdesc:   'Extremely rare barium titanium cyclosilicate found almost exclusively at San Benito County, California. California’s state gem. Exceptionally strong dispersion and UV fluorescence.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-661.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Benitoite',
      refractive_index: { n_omega: 1.804, n_epsilon: 1.756 },
      birefringence:   0.048,
      optical_sign:    '-',
      dispersion:      'Very strong 0.044 — exceeds diamond (0.044 vs 0.044)',
      pleochroism:     'Dichroic: deep blue / nearly colourless',
      fluorescence_lw: 'Weak',
      fluorescence_sw: 'Brilliant blue-white — among the strongest known mineral fluorescence',
      phosphorescence: null,
      visible_wavelength_nm: { min: 430, max: 480 },
      spectra: ['R040052', 'R050335'],
    },

    color: {
      primary_color:          'Sapphire blue — vivid, electric',
      color_variants:         ['Deep sapphire blue', 'Violet-blue', 'Colourless'],
      dominant_wavelength_nm: 455,
      oklch:   { l: 0.45, c: 0.20, h: 262 },
      hex:     '#1e3dbf',
      munsell: '7.5PB 3/12',
      color_temperature_k:    null,
      psychological_effects:  [
        'Rare, singular beauty — the visual experience of scarcity itself',
        'Electric blue at moderate lightness — activating without aggression',
        'Evokes cosmic awareness, stellar consciousness, and singular clarity',
        'The UV fluorescence creates a hidden inner light — the unseen dimension revealed',
      ],
      harmonics: {
        complementary_hue: 82,
        triadic_hues:      [22, 142],
        analogous_range:   [242, 282],
      },
    },

    metaphysical: {
      mineral_name:     'Benitoite',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Crown', 'Throat'],
      element:   ['Water', 'Aether'],
      planet:    ['Uranus', 'Neptune'],
      archetype: ['The Rare Light', 'The Singular Vision', 'The Stellar Emissary'],
      zodiac:    ['Aquarius', 'Virgo', 'Sagittarius'],
      numerology: 9,
      angel_number: 777,
      intention: 'I embody the rare and singular light that I alone can carry.',
      traditions: ['Western crystal healing', 'Gem elixir tradition (indirect method only)'],
      properties: [
        'One of the rarest gemstones on Earth — found almost nowhere else — its very existence teaches singularity',
        'The brilliant SW UV fluorescence represents hidden light made suddenly visible — the unseen self revealed',
        'Activates third eye with unusual clarity and precision rather than the expansive sweep of Azurite',
        'Supports recognition of unique gifts and the courage to embody them fully',
        'Works with stellar and cosmic frequencies — useful in star-being and starseed work',
        'Exceptional dispersion means it scatters light into a full spectrum — it holds all colours within blue',
      ],
      gaia_resonance: 'ClarusLens + QuantumNexus + Noosphere',
      safety_warning: 'Contains barium — do not use for water elixirs. Safe for handling and display. Extremely rare and valuable — handle with exceptional care.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. BERYL
  // Beryllium aluminium cyclosilicate — the parent mineral of Emerald,
  // Aquamarine, Morganite, Heliodor, Goshenite — the royal family of gems
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Beryl',
    mindat_id:   686,
    rruff_ids:   ['R050031', 'R050590', 'R060280'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Black Tourmaline',

    physical: {
      id:           686,
      longid:       'beryl',
      guid:         '',
      name:         'Beryl',
      ima_formula:  'Be₃Al₂Si₆O₁₈',
      mindat_formula: 'Be3Al2Si6O18',
      ima_status:   'A',
      ima_year:     1798,
      strunzten:    '9.CJ.05',
      dana8ed:      '61.1.1.1',
      crystal_system: 'Hexagonal',
      hardness_min: 7.5,
      hardness_max: 8,
      specific_gravity_min: 2.63,
      specific_gravity_max: 2.92,
      cleavage:    'Imperfect on {0001}',
      fracture:    'Conchoidal to uneven',
      tenacity:    'Brittle',
      luster:      ['Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour:      'Colourless (Goshenite), green (Emerald), blue-green (Aquamarine), pink (Morganite), yellow (Heliodor), red (Bixbite)',
      streak:      'White',
      fluorescence: 'Variable — weak to none in most varieties; Emerald: weak red',
      ri_min:      1.564,
      ri_max:      1.602,
      birefringence: 0.006,
      optical_type: 'U',
      shortdesc:   'Hexagonal beryllium aluminium cyclosilicate — the parent species of the entire Beryl gem family including Emerald, Aquamarine, Morganite, Heliodor, and Goshenite.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-686.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name: 'Beryl',
      refractive_index: { n_omega: 1.602, n_epsilon: 1.564 },
      birefringence:   0.006,
      optical_sign:    '-',
      dispersion:      'Weak 0.014',
      pleochroism:     'Weak to moderate depending on variety',
      fluorescence_lw: 'Weak to none (variety-dependent)',
      fluorescence_sw: 'Weak to none',
      phosphorescence: null,
      visible_wavelength_nm: { min: 400, max: 700 },
      spectra: ['R050031', 'R050590', 'R060280'],
    },

    color: {
      primary_color:          'Spectrum entry — all colours possible',
      color_variants:         ['Emerald green', 'Aquamarine blue-green', 'Morganite pink', 'Heliodor yellow', 'Goshenite colourless', 'Bixbite red'],
      dominant_wavelength_nm: null,
      oklch:   { l: 0.70, c: 0.08, h: 155 },
      hex:     null,
      munsell: null,
      color_temperature_k:    null,
      psychological_effects:  [
        'The parent species that contains every colour — embodies the archetype of royal potential',
        'Each variety carries its own complete frequency — Beryl itself is the unmanifest source',
        'Clarity and nobility — the hexagonal perfection of its crystals reflects pure geometric law',
        'Evokes potential unrealised — what could become, held in perfect crystalline form',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   null,
      },
    },

    metaphysical: {
      mineral_name:     'Beryl',
      chakra_primary:   'Crown',
      chakra_secondary: ['Heart', 'Throat', 'Third Eye'],
      element:   ['Water', 'Air', 'Aether'],
      planet:    ['Venus', 'Neptune', 'Moon'],
      archetype: ['The Royal Family', 'The Spectrum Keeper', 'The Noble Potential'],
      zodiac:    ['Gemini', 'Aries', 'Scorpio', 'Taurus'],
      numerology: 11,
      angel_number: 11,
      intention: 'I embody the full spectrum of my potential with nobility and grace.',
      traditions: [
        'Ancient Greek and Roman gem tradition',
        'Vedic gemology — Panna (Emerald) as Mercury stone',
        'Medieval European lapidary tradition',
        'Western crystal healing',
      ],
      properties: [
        'The parent mineral of the royal gem family — Emerald, Aquamarine, Morganite all begin here',
        'Numerology 11 — the master number of illumination — reflects its role as source of many gems',
        'Pure Beryl (Goshenite) is colourless — the unmanifest potential before colour (purpose) arrives',
        'Each coloured variety carries a different aspect of Beryl\'s total frequency spectrum',
        'Supports clarity of purpose, nobility of intention, and royal self-possession',
        'Contains beryllium — handle with care, do not use in water elixirs',
      ],
      gaia_resonance: 'Noosphere + ClarusLens + ViriditasHeart',
      safety_warning: 'Contains beryllium — do not ingest, inhale dust, or use for water elixirs. Beryllium compounds are toxic. Safe for display and careful handling.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. BISMUTH
  // Native bismuth — iridescent hopper crystals — the rainbow metal
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:        'Bismuth',
    mindat_id:   714,
    rruff_ids:   ['R050580'],
    last_synced: '2026-05-29T00:00:00Z',
    trade_name:  false,
    color_layer: 'natural',
    yin_yang_pair: 'Black Tourmaline',

    physical: {
      id:           714,
      longid:       'bismuth',
      guid:         '',
      name:         'Bismuth',
      ima_formula:  'Bi',
      mindat_formula: 'Bi',
      ima_status:   'A',
      ima_year:     1832,
      strunzten:    '1.CA.05',
      dana8ed:      '1.3.5.1',
      crystal_system: 'Trigonal',
      hardness_min: 2,
      hardness_max: 2.5,
      specific_gravity_min: 9.7,
      specific_gravity_max: 9.8,
      cleavage:    'Perfect on {0001}',
      fracture:    'Uneven',
      tenacity:    'Brittle',
      luster:      ['Metallic'],
      diaphaneity: ['Opaque'],
      colour:      'Silver-white with iridescent oxide tarnish — full rainbow spectrum',
      streak:      'Silver-white',
      fluorescence: null,
      ri_min:      null,
      ri_max:      null,
      birefringence: null,
      optical_type: null,
      shortdesc:   'Native bismuth — heavy, low-melting semi-metal forming hopper crystals with spectacular iridescent oxide tarnish. Lab-grown specimens show staircase geometry.',
      updttime:    '2026-05-29T00:00:00Z',
      mindat_url:  'https://www.mindat.org/min-714.html',
      piezoelectric:    false,
      safe_for_water:   false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name: 'Bismuth',
      refractive_index: {},
      birefringence:   null,
      optical_sign:    null,
      dispersion:      null,
      pleochroism:     null,
      fluorescence_lw: null,
      fluorescence_sw: null,
      phosphorescence: null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra: ['R050580'],
    },

    color: {
      primary_color:          'Iridescent rainbow — interference colour from oxide layer',
      color_variants:         ['Silver-white (fresh)', 'Gold', 'Rose pink', 'Violet', 'Cobalt blue', 'Teal green', 'Full rainbow progression'],
      dominant_wavelength_nm: null,
      oklch:   { l: 0.65, c: 0.15, h: 300 },
      hex:     null,
      munsell: null,
      color_temperature_k:    null,
      psychological_effects:  [
        'The full colour spectrum in a single object — embodies totality and transformation',
        'The hopper geometry — staircase steps inward toward a hollow centre — mirrors descent into depth',
        'Iridescence changes with angle — teaches that truth shifts depending on perspective',
        'The rainbow oxide layer is transformation made visible — the base metal becoming light',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [0, 360],
      },
    },

    metaphysical: {
      mineral_name:     'Bismuth',
      chakra_primary:   'Crown',
      chakra_secondary: ['Root', 'Third Eye', 'Sacral', 'Solar Plexus', 'Heart', 'Throat'],
      element:   ['Aether', 'Earth', 'Fire'],
      planet:    ['Uranus', 'Mercury'],
      archetype: ['The Rainbow Transformer', 'The Alchemical Staircase', 'The Prismatic Self'],
      zodiac:    ['Aquarius', 'Gemini'],
      numerology: 2,
      angel_number: 999,
      intention: 'I transform completely. Every layer of me becomes light.',
      traditions: [
        'Alchemical tradition — bismuth as the transitional metal between base and noble',
        'Western crystal healing',
        'Modern energy work — lab-grown hopper crystals widely used',
      ],
      properties: [
        'The hopper crystal geometry — stepped squares spiralling inward — is a physical Fibonacci staircase',
        'Iridescent oxide rainbow: each colour layer is a different thickness of bismuth oxide — physics as metaphor',
        'All seven chakra colours are present simultaneously — a full-spectrum alignment tool',
        'Angel number 999: completion of a major cycle — the rainbow appears after transformation',
        'Supports major life transitions, ego dissolution, and multi-dimensional awareness',
        'Lab-grown hoppers are as energetically valid as natural — the geometry IS the medicine',
        'The heaviest stable non-radioactive element — grounds the entire rainbow into matter',
      ],
      gaia_resonance: 'QuantumNexus + Noosphere + AnchorPrism',
      safety_warning: 'Contains bismuth metal — low toxicity but do not ingest or use for water elixirs. Metallic — keep away from sensitive electronic hardware. Handle with care — brittle and soft (Mohs 2).',
    },
  },

];

export default BATCH_B1;
