/**
 * src/crystals/db/batch-c9a.data.ts
 * GAIA-OS Crystal Database — Batch C-9A
 *
 * Entries:
 *   1. Cornetite        — copper phosphate hydroxide; blue-green; toxic in water
 *   2. Crazy Lace Agate — trade name banded agate from Mexico
 *   3. Creedite         — calcium aluminium fluoro-sulfate hydrate
 *   4. Crocoite         — lead chromate; brilliant orange-red; extreme toxicity
 *   5. Crown of Silver  — trade name for psilomelane/romanèchite-type Mn oxide material
 *
 * Schema: CrystalRecord v1.3
 * Author: GAIA-OS Crystal Intelligence Engine
 * Date:   2026-05-31
 */

import type { CrystalRecord } from './crystal.schema';

const BATCH_C9A: CrystalRecord[] = [
  {
    name: 'Cornetite',
    mindat_id: 1145,
    rruff_ids: ['R060650'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Turquoise',
    physical: {
      id: 1145,
      longid: 'cornetite',
      guid: '',
      name: 'Cornetite',
      ima_formula: 'Cu₃(PO₄)(OH)₃',
      mindat_formula: 'Cu3(PO4)(OH)3',
      ima_status: 'A',
      ima_year: 1916,
      strunzten: '8.BB.35',
      dana8ed: '41.3.2.1',
      crystal_system: 'Orthorhombic',
      hardness_min: 4,
      hardness_max: 4.5,
      specific_gravity_min: 4.22,
      specific_gravity_max: 4.29,
      cleavage: 'Perfect on one direction, imperfect on others',
      fracture: 'Uneven to subconchoidal',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Silky', 'Pearly'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Blue, blue-green, turquoise-blue to greenish blue; often in radiating sprays or fibrous aggregates.',
      streak: 'Pale blue',
      fluorescence: 'None reported',
      ri_min: 1.80,
      ri_max: 1.84,
      birefringence: 0.04,
      optical_type: 'B',
      shortdesc: 'Cornetite — Cu₃(PO₄)(OH)₃, orthorhombic copper phosphate hydroxide. Rich blue to blue-green secondary copper mineral, often in radiating fibrous sprays. H4–4.5. Toxic in water due to copper content.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1145.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Cornetite',
      refractive_index: { n_alpha: 1.80, n_beta: 1.82, n_gamma: 1.84 },
      birefringence: 0.04,
      optical_sign: '+',
      dispersion: 'Moderate',
      pleochroism: 'Weak blue / blue-green',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 480, max: 510 },
      spectra: ['R060650'],
    },
    color: {
      primary_color: 'Turquoise-blue to deep blue-green',
      color_variants: [
        'Sky blue',
        'Turquoise-blue',
        'Blue-green',
        'Greenish blue fibrous sprays',
      ],
      dominant_wavelength_nm: 495,
      oklch: { l: 0.70, c: 0.17, h: 215 },
      hex: '#3da6c6',
      munsell: '5BG 6/8',
      color_temperature_k: null,
      psychological_effects: [
        'Its saturated blue-green tone feels cooling, cleansing, and clarifying.',
        'Radiating crystal sprays create a visual impression of directional energy and expansion.',
        'The copper-rich color field makes it immediately legible as a secondary copper mineral.',
      ],
      harmonics: {
        complementary_hue: 35,
        triadic_hues: [155, 275],
        analogous_range: [195, 235],
      },
    },
    metaphysical: {
      mineral_name: 'Cornetite',
      chakra_primary: 'Throat',
      chakra_secondary: ['Heart', 'Third Eye'],
      element: ['Water', 'Air'],
      planet: ['Mercury', 'Neptune'],
      archetype: ['The Blue Current', 'The Copper Spring'],
      zodiac: ['Gemini', 'Pisces'],
      numerology: 5,
      angel_number: 555,
      intention: 'I speak with clarity carried through living blue currents.',
      traditions: [
        'Named after Belgian geologist Jules Cornet, who worked extensively in the Congo mineral provinces.',
        'Known primarily from oxidized copper deposits in Central Africa.',
        'Modern crystal work values it for communication, mental clarity, and blue-green copper resonance.',
      ],
      properties: [
        'Secondary copper phosphate hydroxide from oxidized copper deposits.',
        'Collector mineral rather than routine jewelry stone due to softness and chemistry.',
        'Not safe for water because copper may leach.',
      ],
      gaia_resonance: 'ClarusLens + ViriditasHeart',
      safety_warning: '⚠️ Copper-bearing mineral. Do not use in water or elixirs. Avoid ingestion and wash hands after handling.',
    },
  },
  {
    name: 'Crazy Lace Agate',
    mindat_id: null,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Laguna Agate',
    physical: {
      id: null,
      longid: 'crazy-lace-agate',
      guid: '',
      name: 'Crazy Lace Agate (trade name banded chalcedony/agate)',
      ima_formula: 'SiO₂',
      mindat_formula: 'SiO2',
      ima_status: 'Not IMA approved — trade name for patterned agate/chalcedony',
      ima_year: null,
      strunzten: '4.DA.05',
      dana8ed: '75.1.3.1',
      crystal_system: 'Trigonal (cryptocrystalline)',
      hardness_min: 6.5,
      hardness_max: 7,
      specific_gravity_min: 2.58,
      specific_gravity_max: 2.64,
      cleavage: 'None',
      fracture: 'Conchoidal',
      tenacity: 'Brittle',
      luster: ['Waxy', 'Vitreous'],
      diaphaneity: ['Translucent', 'Opaque'],
      colour: 'Cream, white, grey, red, orange, yellow, brown in intricate swirling lace-like banding; often called the laughter stone.',
      streak: 'White',
      fluorescence: 'None to weak',
      ri_min: 1.530,
      ri_max: 1.540,
      birefringence: 0.004,
      optical_type: 'U',
      shortdesc: 'Crazy Lace Agate — trade name for intricately banded chalcedony/agate from Mexico, especially Chihuahua. Cream, red, orange, yellow and grey lace-like patterns. H6.5–7. Safe for water.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: null,
      piezoelectric: false,
      safe_for_water: true,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Crazy Lace Agate',
      refractive_index: { n_mean: 1.535 },
      birefringence: 0.004,
      optical_sign: '+',
      dispersion: 'Low',
      pleochroism: 'None',
      fluorescence_lw: 'None to weak',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 580, max: 620 },
      spectra: [],
    },
    color: {
      primary_color: 'Multicolored lace-band agate',
      color_variants: [
        'Cream and red lace',
        'Orange and yellow swirls',
        'Grey-white-red banding',
        'Brown-orange concentric lace',
      ],
      dominant_wavelength_nm: 600,
      oklch: { l: 0.76, c: 0.14, h: 60 },
      hex: '#d49a5b',
      munsell: '10YR 7/8',
      color_temperature_k: null,
      psychological_effects: [
        'The intricate looping bands create movement and visual playfulness.',
        'Its warm palette reads as cheerful, animated, and socially open.',
        'The lace structures evoke complexity without threat, making the stone feel lively rather than chaotic.',
      ],
      harmonics: {
        complementary_hue: 240,
        triadic_hues: [180, 300],
        analogous_range: [40, 80],
      },
    },
    metaphysical: {
      mineral_name: 'Crazy Lace Agate',
      chakra_primary: 'Solar Plexus',
      chakra_secondary: ['Sacral', 'Root'],
      element: ['Fire', 'Earth'],
      planet: ['Sun', 'Mercury'],
      archetype: ['The Laughing Labyrinth', 'The Joy Weaver'],
      zodiac: ['Leo', 'Gemini'],
      numerology: 3,
      angel_number: 333,
      intention: 'I bring joy that dances rather than sits still.',
      traditions: [
        'Strongly associated with Chihuahua, Mexico and marketed as a classic Mexican agate.',
        'Known in crystal culture as the laughter stone or happy lace.',
        'Its popularity grew through lapidary and cabochon work because the patterns polish beautifully.',
      ],
      properties: [
        'Trade name for complexly banded chalcedony/agate.',
        'Durable silica stone suitable for jewelry and handling.',
        'Safe for water and normal everyday use.',
      ],
      gaia_resonance: 'ViriditasHeart + SovereignCore',
      safety_warning: 'Safe for water. Durable silica stone. Normal handling only.',
    },
  },
  {
    name: 'Creedite',
    mindat_id: 1151,
    rruff_ids: ['R060297'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Fluorite',
    physical: {
      id: 1151,
      longid: 'creedite',
      guid: '',
      name: 'Creedite',
      ima_formula: 'Ca₃Al₂(SO₄)(F,OH)₁₀·2H₂O',
      mindat_formula: 'Ca3Al2(SO4)(F,OH)10·2H2O',
      ima_status: 'A',
      ima_year: 1916,
      strunzten: '7.DD.30',
      dana8ed: '31.5.1.1',
      crystal_system: 'Monoclinic',
      hardness_min: 3.5,
      hardness_max: 4,
      specific_gravity_min: 2.66,
      specific_gravity_max: 2.73,
      cleavage: 'Perfect in one direction',
      fracture: 'Uneven to splintery',
      tenacity: 'Brittle',
      luster: ['Vitreous', 'Silky'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Colourless, white, violet, purple, orange, lilac; often in radiating acicular sprays or starbursts.',
      streak: 'White',
      fluorescence: 'Variable; may fluoresce weakly',
      ri_min: 1.46,
      ri_max: 1.49,
      birefringence: 0.03,
      optical_type: 'B',
      shortdesc: 'Creedite — Ca₃Al₂(SO₄)(F,OH)₁₀·2H₂O, monoclinic calcium aluminium fluoro-sulfate hydrate. Often colourless to violet or orange in radiating acicular clusters. H3.5–4. Avoid water due to fluoride-bearing chemistry.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1151.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Creedite',
      refractive_index: { n_alpha: 1.46, n_beta: 1.47, n_gamma: 1.49 },
      birefringence: 0.03,
      optical_sign: '-',
      dispersion: 'Moderate',
      pleochroism: 'None to weak',
      fluorescence_lw: 'Weak variable',
      fluorescence_sw: 'Weak variable',
      phosphorescence: null,
      visible_wavelength_nm: { min: 400, max: 430 },
      spectra: ['R060297'],
    },
    color: {
      primary_color: 'Colourless to violet starburst crystal clusters',
      color_variants: [
        'Colourless',
        'White',
        'Pale lilac',
        'Purple',
        'Orange',
      ],
      dominant_wavelength_nm: 410,
      oklch: { l: 0.84, c: 0.10, h: 305 },
      hex: '#d7c4ea',
      munsell: '5P 8/4',
      color_temperature_k: null,
      psychological_effects: [
        'Its radiating needle clusters create a geometric starburst effect that feels celestial and precise.',
        'The pastel violet range reads as delicate, high-frequency, and carefully structured.',
        'Even when colourless, creedite carries a crystalline complexity that feels articulate rather than plain.',
      ],
      harmonics: {
        complementary_hue: 125,
        triadic_hues: [65, 185],
        analogous_range: [285, 325],
      },
    },
    metaphysical: {
      mineral_name: 'Creedite',
      chakra_primary: 'Crown',
      chakra_secondary: ['Third Eye', 'Throat'],
      element: ['Air', 'Akasha'],
      planet: ['Uranus', 'Moon'],
      archetype: ['The Starburst Archive', 'The Violet Geometry'],
      zodiac: ['Aquarius', 'Pisces'],
      numerology: 7,
      angel_number: 777,
      intention: 'I transmit structure through light and precision through radiance.',
      traditions: [
        'Named from Creede, Colorado, one of the classic localities tied to its discovery history.',
        'Famous violet specimens also come from Durango, Mexico.',
        'Modern crystal collectors value creedite for delicate acicular clusters and unusual chemistry.',
      ],
      properties: [
        'Fluoride-bearing hydrated sulfate mineral.',
        'Collector/display specimen rather than water stone.',
        'Avoid soaking because of chemical sensitivity and possible fluoride leaching.',
      ],
      gaia_resonance: 'ClarusLens + Noosphere',
      safety_warning: '⚠️ Fluoride-bearing mineral. Do not use in water or elixirs. Handle gently; crystals are delicate.',
    },
  },
  {
    name: 'Crocoite',
    mindat_id: 1157,
    rruff_ids: ['R060051'],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: false,
    color_layer: 'natural',
    yin_yang_pair: 'Wulfenite',
    physical: {
      id: 1157,
      longid: 'crocoite',
      guid: '',
      name: 'Crocoite',
      ima_formula: 'PbCrO₄',
      mindat_formula: 'PbCrO4',
      ima_status: 'A',
      ima_year: 1832,
      strunzten: '7.FA.20',
      dana8ed: '30.1.2.1',
      crystal_system: 'Monoclinic',
      hardness_min: 2.5,
      hardness_max: 3,
      specific_gravity_min: 5.9,
      specific_gravity_max: 6.1,
      cleavage: 'Poor to indistinct',
      fracture: 'Subconchoidal to uneven',
      tenacity: 'Brittle',
      luster: ['Adamantine', 'Vitreous'],
      diaphaneity: ['Transparent', 'Translucent'],
      colour: 'Brilliant orange-red to scarlet-red, most often as long prismatic crystals; among the most visually striking toxic minerals.',
      streak: 'Orange-yellow',
      fluorescence: 'None',
      ri_min: 2.31,
      ri_max: 2.66,
      birefringence: 0.35,
      optical_type: 'B',
      shortdesc: 'Crocoite — PbCrO₄, monoclinic lead chromate. Brilliant orange-red prismatic crystals, especially famous from Dundas, Tasmania. H2.5–3, SG 5.9–6.1. Extremely toxic due to lead and hexavalent chromium.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: 'https://www.mindat.org/min-1157.html',
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Crocoite',
      refractive_index: { n_alpha: 2.31, n_beta: 2.44, n_gamma: 2.66 },
      birefringence: 0.35,
      optical_sign: '+',
      dispersion: 'Strong',
      pleochroism: 'Orange-red / yellow-orange',
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: { min: 605, max: 635 },
      spectra: ['R060051'],
    },
    color: {
      primary_color: 'Brilliant orange-red',
      color_variants: [
        'Orange-red prisms',
        'Scarlet-red',
        'Red-orange transparent crystals',
        'Yellow-orange altered tones',
      ],
      dominant_wavelength_nm: 620,
      oklch: { l: 0.60, c: 0.24, h: 40 },
      hex: '#e85a1c',
      munsell: '5YR 6/14',
      color_temperature_k: null,
      psychological_effects: [
        'Crocoite is visually electric, almost impossible to ignore in a display cabinet.',
        'Its long red-orange prisms create a sense of danger, flare, and high intensity.',
        'The brilliance is heightened by the knowledge that the chemistry is among the most hazardous in the mineral world.',
      ],
      harmonics: {
        complementary_hue: 220,
        triadic_hues: [160, 280],
        analogous_range: [20, 60],
      },
    },
    metaphysical: {
      mineral_name: 'Crocoite',
      chakra_primary: 'Sacral',
      chakra_secondary: ['Root', 'Solar Plexus'],
      element: ['Fire', 'Earth'],
      planet: ['Mars', 'Pluto'],
      archetype: ['The Hazard Flame', 'The Red Signal'],
      zodiac: ['Aries', 'Scorpio'],
      numerology: 9,
      angel_number: 999,
      intention: 'I burn bright enough to warn as well as attract.',
      traditions: [
        'World-famous specimens come from Dundas, Tasmania, which defines the species in collector culture.',
        'Historically important as a lead chromate mineral tied to chromium chemistry.',
        'Now primarily a cabinet mineral because of toxicity and fragility.',
      ],
      properties: [
        'Contains lead and hexavalent chromium, making it extremely hazardous.',
        'Never use in water, bodywork, elixirs, or children-facing settings.',
        'Best displayed sealed and handled minimally.',
      ],
      gaia_resonance: 'SovereignCore + AnchorPrism',
      safety_warning: '🚨 EXTREME TOXICITY — contains lead and hexavalent chromium. Never use in water. Do not ingest, inhale dust, or handle excessively. Wash hands immediately after contact.',
    },
  },
  {
    name: 'Crown of Silver',
    mindat_id: null,
    rruff_ids: [],
    last_synced: '2026-05-31T00:00:00Z',
    trade_name: true,
    color_layer: 'natural',
    yin_yang_pair: 'Hematite',
    physical: {
      id: null,
      longid: 'crown-of-silver',
      guid: '',
      name: 'Crown of Silver (trade name; typically psilomelane/romanèchite-type Mn oxide material)',
      ima_formula: 'BaMn²⁺Mn⁴⁺₈O₁₆(OH)₄ (approx. romanèchite-type)',
      mindat_formula: 'Variable manganese oxide-hydroxide',
      ima_status: 'Not IMA approved — trade name, commonly applied to psilomelane / romanèchite material',
      ima_year: null,
      strunzten: '4th ed. oxides/hydroxides group equivalent',
      dana8ed: null,
      crystal_system: 'Monoclinic to mixed massive habit (trade material)',
      hardness_min: 5,
      hardness_max: 6,
      specific_gravity_min: 4.2,
      specific_gravity_max: 4.8,
      cleavage: 'Indistinct',
      fracture: 'Uneven to subconchoidal',
      tenacity: 'Brittle',
      luster: ['Submetallic', 'Metallic', 'Silky'],
      diaphaneity: ['Opaque'],
      colour: 'Metallic black to dark steel-grey with silvery botryoidal or reniform highlights giving the appearance of a silver crown over black body.',
      streak: 'Brownish black',
      fluorescence: 'None',
      ri_min: null,
      ri_max: null,
      birefringence: null,
      optical_type: null,
      shortdesc: 'Crown of Silver — trade name usually applied to botryoidal psilomelane/romanèchite-type manganese oxide material with metallic silver-grey highlights. H5–6. Opaque. Not safe for water as a manganese oxide trade material.',
      updttime: '2026-05-31T00:00:00Z',
      mindat_url: null,
      piezoelectric: false,
      safe_for_water: false,
      safe_for_hardware: false,
    },
    optical: {
      mineral_name: 'Crown of Silver',
      refractive_index: null,
      birefringence: null,
      optical_sign: null,
      dispersion: null,
      pleochroism: null,
      fluorescence_lw: 'None',
      fluorescence_sw: 'None',
      phosphorescence: null,
      visible_wavelength_nm: null,
      spectra: [],
    },
    color: {
      primary_color: 'Silvery metallic-black',
      color_variants: [
        'Steel-grey sheen on black',
        'Silvery botryoidal crusts',
        'Dark metallic grey',
        'Black manganese mass with bright silver highlight',
      ],
      dominant_wavelength_nm: null,
      oklch: { l: 0.35, c: 0.02, h: 250 },
      hex: '#666a70',
      munsell: 'N 4/',
      color_temperature_k: null,
      psychological_effects: [
        'The silver-over-black contrast reads as armored, regal, and protective.',
        'Botryoidal forms create an organic crown-like texture that justifies the trade name.',
        'The metallic sheen gives it a ceremonial rather than decorative presence.',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues: null,
        analogous_range: null,
      },
    },
    metaphysical: {
      mineral_name: 'Crown of Silver',
      chakra_primary: 'Crown',
      chakra_secondary: ['Root'],
      element: ['Metal', 'Earth'],
      planet: ['Saturn', 'Moon'],
      archetype: ['The Silver Regent', 'The Protective Diadem'],
      zodiac: ['Capricorn', 'Aquarius'],
      numerology: 8,
      angel_number: 888,
      intention: 'I place a cool crown over the mind while anchoring the body below.',
      traditions: [
        'Used in trade as a poetic name for metallic manganese oxide material, often psilomelane/romanèchite type.',
        'Valued for its silvery botryoidal appearance rather than a formal mineral species identity.',
        'Modern crystal culture associates it with protection, emotional steadiness, and meditative containment.',
      ],
      properties: [
        'Trade-name material with variable exact composition by specimen and seller.',
        'Usually treated as manganese oxide-rich and therefore not suitable for water use.',
        'Best handled as a display or meditation stone rather than an elixir stone.',
      ],
      gaia_resonance: 'AnchorPrism + SovereignCore',
      safety_warning: '⚠️ Trade-name manganese oxide material. Do not use in water or elixirs. Wash hands after handling and avoid dust.',
    },
  },
];

export default BATCH_C9A;
