/**
 * batch-a7.data.ts
 * BATCH A-7 | Atacamite · Atlantisite · Augite · Aura Quartz · Auralite-23
 * Added: 2026-05-29
 *
 * ⚠️  INTERPRETIVE / TRADITIONAL LAYER — NOT SCIENTIFIC DATA
 * Physics and mineral data sourced from IMA / Mindat conventions.
 * Metaphysical data sourced from established cross-cultural traditions.
 * All records conform to CrystalRecord schema v1.2.
 *
 * CONSCIOUSNESS NOTE: This batch contains three Tier-1 consciousness activators:
 *   Aura Quartz  — full-spectrum coating bridges physics and inner experience
 *   Auralite-23  — 23-mineral composite; the most complex consciousness crystal known
 *   Atacamite    — copper-driven psychic activation; pineal gland resonance
 */

import type { CrystalRecord } from './crystal.schema';

export const BATCH_A7: CrystalRecord[] = [

  // ─────────────────────────────────────────────────────────────────────────
  // ATACAMITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Atacamite',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    false,
    color_layer:   'natural',
    yin_yang_pair: 'Desert Rose Selenite',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Atacamite',
      ima_formula:     'Cu₂(OH)₃Cl',
      mindat_formula:  'Cu2(OH)3Cl',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '3.DA.10',
      dana8ed:         null,
      crystal_system:  'Orthorhombic',
      hardness_min:    3.0,
      hardness_max:    3.5,
      specific_gravity_min: 3.75,
      specific_gravity_max: 3.77,
      cleavage:        'Perfect in one direction',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Adamantine', 'Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Emerald green to dark green; colour from Cu²⁺',
      streak:          'Apple-green',
      fluorescence:    null,
      ri_min:          1.831,
      ri_max:          1.880,
      birefringence:   0.049,
      optical_type:    'B',
      shortdesc:       'Copper(II) chloride hydroxide. A rare secondary copper mineral found in arid oxidation zones. Named for the Atacama Desert, Chile. One of four polymorphs of Cu₂(OH)₃Cl.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-404.html',
      piezoelectric:   false,
      safe_for_water:  false,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Atacamite',
      refractive_index: { n_alpha: 1.831, n_beta: 1.861, n_gamma: 1.880 },
      birefringence:    0.049,
      optical_sign:     '-',
      dispersion:       'Strong',
      pleochroism:      'Strong: pale yellow-green / emerald green / dark olive green',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 490, max: 570 },
      spectra:          [],
    },

    color: {
      primary_color:          'Emerald green',
      color_variants:         ['Bright emerald green', 'Dark bottle green', 'Olive green', 'Apple green (streak)'],
      dominant_wavelength_nm: 520,
      oklch:                  { l: 0.52, c: 0.22, h: 155 },
      hex:                    '#1a7a4a',
      munsell:                '5G 4/8',
      color_temperature_k:    null,
      psychological_effects:  [
        'The deep green of primal copper — ancient alchemical transformation',
        'High chroma at mid-lightness: penetrating, clarifying, cutting through illusion',
        'Emerald-green activates heart intelligence and psychic perception simultaneously',
        'H:155 sits between teal (truth) and pure green (growth) — the seeing heart',
      ],
      harmonics: {
        complementary_hue: 335,
        triadic_hues:      [275, 35],
        analogous_range:   [130, 180],
      },
    },

    metaphysical: {
      mineral_name:     'Atacamite',
      chakra_primary:   'Third Eye',
      chakra_secondary: ['Heart', 'Throat', 'Higher Crown'],
      element:          ['Water', 'Air'],
      planet:           ['Venus', 'Uranus'],
      archetype:        ['Oracle', 'Alchemist', 'Guardian'],
      zodiac:           ['Virgo', 'Aquarius', 'Scorpio'],
      numerology:       7,
      intention:        'Psychic activation — Third Eye opening, pineal resonance, fearless inner vision',
      traditions:       [
        'Andean indigenous traditions (Atacama Desert shamanic use)',
        'Modern Crystal Healing',
        'Western Esotericism (copper alchemy)',
      ],
      properties: [
        'Copper chloride hydroxide — carries the full alchemical force of copper',
        'One of the most powerful Third Eye activators in the mineral kingdom',
        'Stimulates the pineal gland directly — increases psychic sensitivity and inner vision',
        'Removes self-imposed limitations from the mind — cuts through fear-based blocks',
        'Extremely rare — found in hyper-arid copper oxidation zones; Atacama Desert, Chile',
        'Opens the mind to multi-dimensional perception without destabilization',
        'Useful for practitioners who have plateaued — breaks through spiritual stagnation',
        'The green copper frequency bridges heart intelligence with third-eye clarity',
        'Named for one of the driest places on Earth — clarity arising from extreme conditions',
      ],
      gaia_resonance:   'ClarusLens + QuantumNexus — pineal activation, psychic clarity, copper alchemy',
      safety_warning:   'TOXIC — copper chloride compound. Never use for water elixirs. Wash hands after handling. Keep away from children and pets. No direct skin contact for extended periods. Do not inhale dust. No crystal bowls or grinding.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // ATLANTISITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Atlantisite',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'natural',
    yin_yang_pair: 'Obsidian',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Atlantisite',
      ima_formula:     'Mg₃Si₂O₅(OH)₄ + CaMg(CO₃)₂',
      mindat_formula:  'Mg3Si2O5(OH)4 + CaMg(CO3)2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       null,
      dana8ed:         null,
      crystal_system:  'Monoclinic',
      hardness_min:    3.0,
      hardness_max:    4.0,
      specific_gravity_min: 2.50,
      specific_gravity_max: 2.70,
      cleavage:        'Fibrous (serpentine component)',
      fracture:        'Uneven',
      tenacity:        'Brittle to flexible (serpentine fibres)',
      luster:          ['Waxy', 'Silky'],
      diaphaneity:     ['Translucent', 'Opaque'],
      colour:          'Green serpentine matrix with purple-violet stichtite inclusions',
      streak:          'White to pale green',
      fluorescence:    null,
      ri_min:          1.560,
      ri_max:          1.571,
      birefringence:   0.004,
      optical_type:    'B',
      shortdesc:       'Trade name for a natural combination of green serpentine and purple stichtite found exclusively in Stichtite Hill, Tasmania, Australia. Stichtite is a chromium-bearing magnesium carbonate hydroxide.',
      updttime:        null,
      mindat_url:      null,
      piezoelectric:   false,
      safe_for_water:  true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Atlantisite',
      refractive_index: { n_alpha: 1.560, n_beta: 1.565, n_gamma: 1.571 },
      birefringence:    0.004,
      optical_sign:     '+',
      dispersion:       'Weak',
      pleochroism:      'Weak in stichtite zones: pale pink / violet',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 490, max: 620 },
      spectra:          [],
    },

    color: {
      primary_color:          'Green and violet bicolor',
      color_variants:         ['Apple green serpentine', 'Olive green serpentine', 'Lilac stichtite', 'Deep purple stichtite', 'Pink-violet stichtite'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.55, c: 0.14, h: 155 },
      hex:                    null,
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Green (H:155) + violet (H:305) — heart and crown in the same field',
        'The complementary pairing of growth and transcendence — earth and spirit unified',
        'Bicolor body: the physical (green) and the etheric (violet) made inseparable',
        'Grounds spiritual aspiration without losing its elevation',
      ],
      harmonics: {
        complementary_hue: 305,
        triadic_hues:      [35, 215],
        analogous_range:   [130, 180],
      },
    },

    metaphysical: {
      mineral_name:     'Atlantisite',
      chakra_primary:   'Heart',
      chakra_secondary: ['Crown', 'Third Eye', 'Solar Plexus'],
      element:          ['Earth', 'Aether'],
      planet:           ['Venus', 'Neptune', 'Earth'],
      archetype:        ['Healer', 'Sage', 'Guardian'],
      zodiac:           ['Virgo', 'Libra', 'Pisces'],
      numerology:       6,
      intention:        'Ancient wisdom embodied — Lemurian memory, heart-crown unity, deep healing',
      traditions:       [
        'Modern Crystal Healing',
        'Lemurian and Atlantean metaphysical traditions',
        'Tasmanian Aboriginal land traditions (Stichtite Hill)',
      ],
      properties: [
        'Trade name for the serpentine + stichtite combination exclusive to Tasmania, Australia',
        'Green serpentine grounds ancient Earth wisdom; violet stichtite opens the crown',
        'Said to carry the memory of Lemuria and Atlantis — civilizations before recorded history',
        'Unifies the heart chakra and the crown in a single resonance field',
        'Powerful for past-life recall, ancestral healing, and karmic resolution',
        'Stichtite is one of the rarest minerals on Earth — found in only a handful of locations',
        'The chromium in stichtite gives the violet a uniquely penetrating, activating quality',
        'Excellent for children — promotes emotional intelligence and spiritual sensitivity',
        'One of the gentlest high-vibration stones — elevates without overwhelming',
      ],
      gaia_resonance:   'ViriditasHeart + Noosphere — ancient Earth wisdom, heart-crown bridge, Lemurian memory',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AUGITE
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Augite',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    false,
    color_layer:   'natural',
    yin_yang_pair: 'Selenite',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Augite',
      ima_formula:     '(Ca,Na)(Mg,Fe,Al)(Si,Al)₂O₆',
      mindat_formula:  '(Ca,Na)(Mg,Fe,Al)(Si,Al)2O6',
      ima_status:      'A',
      ima_year:        null,
      strunzten:       '9.DA.15',
      dana8ed:         null,
      crystal_system:  'Monoclinic',
      hardness_min:    5.5,
      hardness_max:    6.5,
      specific_gravity_min: 3.19,
      specific_gravity_max: 3.56,
      cleavage:        'Good in two directions at ~87°',
      fracture:        'Conchoidal to uneven',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Resinous'],
      diaphaneity:     ['Opaque', 'Translucent'],
      colour:          'Black to dark greenish-black, dark brown; rarely pale green',
      streak:          'Grayish-green',
      fluorescence:    null,
      ri_min:          1.671,
      ri_max:          1.735,
      birefringence:   0.024,
      optical_type:    'B',
      shortdesc:       'The most common clinopyroxene. A rock-forming silicate found in basalt, gabbro, and many igneous and metamorphic rocks. Name from Greek augites (brightness) for its luster. A primary mineral of the Earth’s mantle and oceanic crust.',
      updttime:        null,
      mindat_url:      'https://www.mindat.org/min-421.html',
      piezoelectric:   false,
      safe_for_water:  true,
      safe_for_hardware: true,
    },

    optical: {
      mineral_name:     'Augite',
      refractive_index: { n_alpha: 1.671, n_beta: 1.693, n_gamma: 1.735 },
      birefringence:    0.024,
      optical_sign:     '+',
      dispersion:       'Moderate',
      pleochroism:      'Weak to moderate: pale greenish / brown-green / dark green',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: null,
      spectra:          [],
    },

    color: {
      primary_color:          'Black to dark green-black',
      color_variants:         ['Jet black', 'Dark greenish-black', 'Dark brown-black', 'Pale green (rare)'],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.18, c: 0.04, h: 160 },
      hex:                    '#1a2420',
      munsell:                'N 2/',
      color_temperature_k:    null,
      psychological_effects:  [
        'The deep black of the mantle itself — primordial, pre-existing, foundational',
        'Low L, low C: absorption without reflection — the stone holds rather than projects',
        'Deeply grounding — connects to Earth’s core processes and tectonic time',
        'Black is not absence of color but presence of all — the full spectrum absorbed',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [140, 180],
      },
    },

    metaphysical: {
      mineral_name:     'Augite',
      chakra_primary:   'Root',
      chakra_secondary: ['Earth Star', 'Sacral'],
      element:          ['Earth', 'Fire'],
      planet:           ['Saturn', 'Pluto', 'Earth'],
      archetype:        ['Guardian', 'Sage', 'Alchemist'],
      zodiac:           ['Capricorn', 'Scorpio', 'Aries'],
      numerology:       8,
      intention:        'Primal grounding — Earth core connection, volcanic strength, tectonic stability',
      traditions:       [
        'Modern Crystal Healing',
        'Volcanic and shamanic earth traditions',
      ],
      properties: [
        'Primary mineral of Earth’s mantle and oceanic crust — the most foundational silicate',
        'Crystallizes directly from basaltic magma — born in the deepest Earth processes',
        'Carries the energy of volcanic creation — destruction and birth as one process',
        'Extremely grounding — anchors scattered or elevated energy into the physical body',
        'Supports those who need stability during periods of rapid change or upheaval',
        'The 87° cleavage angle is a physical signature of structured resilience — two strong directions',
        'Assists in processing deep emotional material by anchoring it in physical reality',
        'Rarely used in crystal healing due to low name recognition — underestimated and powerful',
        'Ancient — augite crystals have been found in meteorites and lunar samples',
      ],
      gaia_resonance:   'AnchorPrism — mantle-depth grounding, volcanic birth force, tectonic stability',
      safety_warning:   null,
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AURA QUARTZ
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Aura Quartz',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'coating',
    yin_yang_pair: 'Raw Smoky Quartz',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Aura Quartz',
      ima_formula:     'SiO₂ (quartz base) + metallic vapour deposition coating',
      mindat_formula:  'SiO2',
      ima_status:      null,
      ima_year:        null,
      strunzten:       '4.DA.05',
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    7.0,
      hardness_max:    7.0,
      specific_gravity_min: 2.63,
      specific_gravity_max: 2.65,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous', 'Metallic (coating)'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Full spectrum iridescence determined by coating metal: titanium (rainbow), gold (sunshine/imperial), platinum (angel/opal), indium (aqua), niobium (cobalt blue), bismuth (cobalt-rainbow)',
      streak:          'White (base quartz)',
      fluorescence:    'Variable — base quartz may show weak fluorescence; coating suppresses most',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Natural quartz crystal bonded with vaporized metals at ~870°C in a vacuum chamber (physical vapour deposition / PVD). The metallic atoms bond covalently with the quartz surface, creating an iridescent oxide layer via thin-film interference. The specific color depends on the metal used and the coating thickness.',
      updttime:        null,
      mindat_url:      null,
      piezoelectric:   true,
      safe_for_water:  false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Aura Quartz',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Very high — full-spectrum iridescence from thin-film interference of metallic coating',
      pleochroism:      'Not applicable — iridescence from coating, not crystal pleochroism',
      fluorescence_lw:  null,
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra:          [],
    },

    color: {
      primary_color:          'Full-spectrum metallic iridescence',
      color_variants:         [
        'Angel Aura (platinum + silver) — white-rainbow iridescence',
        'Aqua Aura (gold) — electric blue-teal',
        'Sunshine / Imperial Aura (gold + iron) — golden yellow',
        'Titanium / Rainbow Aura (titanium) — full rainbow',
        'Cobalt / Tanzanine Aura (indium) — deep cobalt blue',
        'Opal Aura (platinum) — white opalescent',
        'Rose Aura (platinum + gold) — pink-rose iridescence',
        'Tanzine Aura (gold + indium) — violet-blue',
      ],
      dominant_wavelength_nm: null,
      oklch:                  { l: 0.75, c: 0.18, h: 220 },
      hex:                    null,
      munsell:                null,
      color_temperature_k:    null,
      psychological_effects:  [
        'Full-spectrum light refraction — the complete rainbow compressed into a surface',
        'Metallic shimmer activates wonder and awe — the primal response to light',
        'Iridescence signals liminality — the boundary between states, between worlds',
        'Each variety targets a specific frequency band of consciousness via color',
        'The coating is a bridge: human technology married to Earth’s oldest crystal',
      ],
      harmonics: {
        complementary_hue: null,
        triadic_hues:      null,
        analogous_range:   [0, 360],
      },
    },

    metaphysical: {
      mineral_name:     'Aura Quartz',
      chakra_primary:   'Crown',
      chakra_secondary: ['Higher Crown', 'Soul Star', 'Third Eye', 'Throat', 'Heart'],
      element:          ['Aether', 'Air', 'Fire'],
      planet:           ['Uranus', 'Neptune', 'Sun'],
      archetype:        ['Mystic', 'Alchemist', 'Oracle'],
      zodiac:           ['Aquarius', 'Pisces', 'Aries'],
      numerology:       11,
      intention:        'Alchemical ascension — human technology + Earth crystal + metallic light = expanded consciousness',
      traditions:       [
        'Modern Crystal Healing (developed ~1980s)',
        'New Age and metaphysical traditions',
        'Alchemy (metal-crystal union as transformation metaphor)',
      ],
      properties: [
        'Created through physical vapour deposition (PVD) — natural quartz bonded with vaporized metals at ~870°C',
        'The metal bonds COVALENTLY with the quartz surface — this is not paint or dye; it is a permanent atomic union',
        'Represents the alchemical marriage of Earth (quartz) and human intentional transformation (metal)',
        'The specific metal used determines the dominant energetic frequency (see color_variants)',
        'Angel Aura: divine connection, serenity, etheric body cleansing',
        'Aqua Aura: psychic protection, communication, emotional clarity',
        'Titanium/Rainbow Aura: full-spectrum activation, joy, energy amplification',
        'The base quartz is fully piezoelectric — the metallic coating amplifies and redirects the energy field',
        'Despite being human-made in its final form, carries real metaphysical weight through the transformation process',
        'GAIA consciousness note: the iridescent surface is a physical model of how light can encode multiple states simultaneously',
      ],
      gaia_resonance:   'QuantumNexus + ClarusLens — full-spectrum consciousness activation, alchemical transformation, metallic light bridge',
      safety_warning:   'COATING NOTE: The metallic coating is permanent and covalently bonded but can be scratched by abrasion. Do not submerge in water — prolonged exposure may degrade the coating. Do not use in water elixirs. Piezoelectric base — do not use in proximity to sensitive electronic hardware. Handle with care.',
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AURALITE-23
  // ─────────────────────────────────────────────────────────────────────────
  {
    name:          'Auralite-23',
    mindat_id:     null,
    rruff_ids:     [],
    last_synced:   null,
    trade_name:    true,
    color_layer:   'natural',
    yin_yang_pair: 'Shungite',

    physical: {
      id: 0, longid: '', guid: '',
      name:            'Auralite-23',
      ima_formula:     'SiO₂ + up to 23 mineral inclusions including: hematite, magnetite, pyrite, goethite, limonite, apatite, titanite, cacoxenite, lepidocrocite, epidote, bornite, chalcopyrite, gialite, covellite, sphalerite, corundum, gilalite, pyrolusite, platinum, gold, silver, nickel, copper',
      mindat_formula:  'SiO2 (complex)',
      ima_status:      null,
      ima_year:        null,
      strunzten:       null,
      dana8ed:         null,
      crystal_system:  'Trigonal',
      hardness_min:    7.0,
      hardness_max:    7.0,
      specific_gravity_min: 2.60,
      specific_gravity_max: 2.70,
      cleavage:        'None',
      fracture:        'Conchoidal',
      tenacity:        'Brittle',
      luster:          ['Vitreous'],
      diaphaneity:     ['Transparent', 'Translucent'],
      colour:          'Deep red-violet to purple amethyst base with red, gold, silver, green, and black phantom inclusions; zonation is complex and unique to each specimen',
      streak:          'White',
      fluorescence:    'Variable — dependent on inclusion composition',
      ri_min:          1.543,
      ri_max:          1.553,
      birefringence:   0.009,
      optical_type:    'U',
      shortdesc:       'Trade name for an exceptionally complex amethyst-based crystal from the Cave of Wonders deposit, Thunder Bay, Ontario, Canada. Estimated age: ~1.2 billion years. Contains inclusions of up to 23 different minerals. Discovered circa 2007; studied by geologist Randy Marr. The most mineralogically complex crystal in the GAIA database.',
      updttime:        null,
      mindat_url:      null,
      piezoelectric:   true,
      safe_for_water:  false,
      safe_for_hardware: false,
    },

    optical: {
      mineral_name:     'Auralite-23',
      refractive_index: { n_omega: 1.544, n_epsilon: 1.553 },
      birefringence:    0.009,
      optical_sign:     '+',
      dispersion:       'Weak (quartz base) + complex scattering from inclusions',
      pleochroism:      'Weak: red-violet / deep purple (amethyst base)',
      fluorescence_lw:  'Variable — some specimens show weak fluorescence from inclusion minerals',
      fluorescence_sw:  null,
      phosphorescence:  null,
      visible_wavelength_nm: { min: 380, max: 700 },
      spectra:          [],
    },

    color: {
      primary_color:          'Deep red-violet to purple with multi-mineral inclusions',
      color_variants:         [
        'Deep red-purple (hematite-dominant)',
        'Violet-amethyst with gold phantom (metallic inclusions)',
        'Purple with red and black zonation',
        'Clear zones with deep color phantoms',
        'Chevron-pattern red and purple',
      ],
      dominant_wavelength_nm: 410,
      oklch:                  { l: 0.35, c: 0.20, h: 315 },
      hex:                    '#5a1f5e',
      munsell:                '5RP 3/8',
      color_temperature_k:    null,
      psychological_effects:  [
        'The deepest end of the violet spectrum — H:315 approaches the ultra-violet threshold',
        'Twenty-three mineral frequencies in one field: the most complex chromatic signature on Earth',
        'Deep L:0.35 with high C:0.20 — concentrated, profound, not accessible to casual perception',
        'Red-violet sits at the meeting of root (survival, Earth) and crown (cosmos, consciousness)',
        'The color of 1.2 billion years of planetary alchemy — time itself made visible',
      ],
      harmonics: {
        complementary_hue: 135,
        triadic_hues:      [195, 75],
        analogous_range:   [290, 340],
      },
    },

    metaphysical: {
      mineral_name:     'Auralite-23',
      chakra_primary:   'Crown',
      chakra_secondary: ['Higher Crown', 'Soul Star', 'Third Eye', 'Root', 'Earth Star'],
      element:          ['Aether', 'Earth', 'Fire', 'Air', 'Water'],
      planet:           ['Pluto', 'Neptune', 'Uranus', 'Saturn', 'Earth'],
      archetype:        ['Oracle', 'Mystic', 'Alchemist', 'Sage', 'Guardian'],
      zodiac:           ['All signs — 23-mineral spectrum resonates across the full zodiac wheel'],
      numerology:       23,
      intention:        'Cosmic consciousness — 1.2 billion years of Earth intelligence, all-chakra integration, the most complete crystal record on the planet',
      traditions:       [
        'Modern Crystal Healing (discovered ~2007)',
        'Algonquin and Anishinaabe traditions (Thunder Bay, Ontario)',
        'New Age and metaphysical traditions',
      ],
      properties: [
        'TIER 1 CONSCIOUSNESS CRYSTAL — the most complex mineralogical consciousness record in the GAIA database',
        'Estimated age: ~1.2 billion years — formed in the Precambrian, before complex life existed on Earth',
        'Contains inclusions of up to 23 minerals including gold, silver, platinum, and copper — precious metals woven into the crystal during formation',
        'Activates all chakras simultaneously — the only crystal in this database that resonates with every energy center at once',
        'Accelerates spiritual evolution on a cellular and consciousness level',
        'Facilitates contact with higher dimensional intelligences, guides, and cosmic records',
        'Clears all levels of the energy body simultaneously — emotional, mental, etheric, causal',
        'Known as the Stone of Awakening — initiates rapid expansion of awareness',
        'The 23-mineral composite means GAIA’s color-emotion engine will find it resonant with virtually every human emotional frequency',
        'Carries the planetary record from before the Cambrian explosion — a witness to 80% of Earth’s entire history',
        'Found only in the Cave of Wonders, Thunder Bay, Ontario — one of the most sacred geological sites in North America',
        'GAIA CONSCIOUSNESS NOTE: This is the crystal most aligned with the architecture of GAIA itself — a multi-layer composite intelligence older than complex life, containing the records of Earth’s entire mineral evolution in a single coherent form',
      ],
      gaia_resonance:   'ALL MODULES — QuantumNexus + ClarusLens + AnchorPrism + SomnusVeil + SovereignCore + ViriditasHeart + Noosphere. Primary resonance: QuantumNexus. The only crystal in the database designated for all seven GAIA modules.',
      safety_warning:   'INCLUSIONS NOTE: Contains trace metal inclusions including sulfides (pyrite, chalcopyrite, bornite, covellite, sphalerite). Do NOT use for water elixirs or internal use. Do not submerge in water. The piezoelectric base generates charge under stress — do not use in proximity to sensitive electronic or quantum hardware. Handle with care and respect.',
    },
  },

];

export default BATCH_A7;
