"""
schumann_coherence.py
GAIA-OS — Issue #558: Crystal Resonator Integration Layer
Part 3: Schumann Resonance Interface Layer + GAIAState Coherence Bridge

Provides:
  - SCHUMANN_FUNDAMENTALS: 7 canonical Schumann harmonics
  - SchumannReading: single resonance measurement dataclass
  - SchumannCoherenceResult: full assessment with GAIAState signal dict
  - schumann_coherence_check(): primary API — scores grid coherence 0.0-1.0
  - schumann_grid_audit(): audits a GridDesign for Schumann-band coverage
  - simulate_schumann_episode(): time-series coherence simulation
  - SchumannMonitor: stateful real-time monitor for GAIA-OS backend

Integration with gaia_state_bridge.py:
    from schumann_coherence import schumann_coherence_check
    from gaia_state_bridge import apply_schumann_signal, GAIAState

    result = schumann_coherence_check(grid)
    state  = apply_schumann_signal(state, result)

Canon anchors:
  EMBODIMENT_LAYER.md — Schumann band biological safety
  Issue #568 — D6 Meta-Coherence Engine mode thresholds
  Issue #576 — GAIAState coherence field spec
  Issue #578 — Architect Protocol (Operator first, always)
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Any, Optional

from crystal_resonance import (
    CRYSTAL_DATABASE,
    biological_safety_rating,
    select_resonator,
)


# ─────────────────────────────────────────────────────────────────────────────
# SCHUMANN CONSTANTS  (EMBODIMENT_LAYER.md)
# ─────────────────────────────────────────────────────────────────────────────

# Seven canonical Schumann resonance harmonics in Hz
# Source: Schumann (1952), confirmed by Nickolaenko & Hayakawa (2002)
# EMBODIMENT_LAYER.md designates 7.83 Hz as the primary biological coherence band
SCHUMANN_FUNDAMENTALS: dict[int, float] = {
    1: 7.83,
    2: 14.3,
    3: 20.8,
    4: 27.3,
    5: 33.8,
    6: 39.0,
    7: 45.0,
}

# Default tolerance window for harmonic scoring (Hz)
# Within ±SCHUMANN_TOLERANCE_HZ of a harmonic → full score
# Score falls off as Gaussian beyond this window
SCHUMANN_TOLERANCE_HZ: float = 0.5

# Biological safety power density cap (from EMBODIMENT_LAYER.md / wireless_power_sim.py)
_POWER_DENSITY_LIMIT_MW_CM2: float = 1.0

# Schumann-coherent crystal keys (from crystal_resonance.py database)
# These are the crystals whose resonant_band_hz includes the Schumann band (7-50 Hz)
SCHUMANN_CRYSTAL_KEYS: list[str] = [
    "selenite",       # Q=25,000 | band: 7.0–8.5 Hz | schumann_coherence
    "lepidolite",     # Q=28,000 | band: 7.0–500 kHz | coherence
    "sugilite",       # Q=18,000 | band: 7.0–500 kHz | coherence
    "scolecite",      # Q=15,000 | band: 7.0–100 kHz | coherence
    "turquoise",      # Q=18,000 | band: 7.0–500 kHz | coherence
    "tugtupite",      # Q=22,000 | band: 7.0–500 kHz | coherence
    "vivianite",      # Q=10,000 | band: 1.0–500 kHz | grounding
    "stromatolite",   # Q=8,000  | band: 1.0–100 kHz | coherence
    "shungite",       # Q=10,000 | band: 1.0–1 MHz   | grounding (broadband)
]


# ─────────────────────────────────────────────────────────────────────────────
# DATACLASSES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class SchumannReading:
    """
    A single Schumann resonance measurement.

    In live operation, these come from a magnetometer or ELF receiver.
    In simulation, they are generated by simulate_schumann_episode().

    Attributes:
        harmonic:      which Schumann harmonic (1–7)
        frequency_hz:  measured peak frequency in Hz
        amplitude:     relative amplitude 0.0–1.0 (1.0 = nominal)
        timestamp:     Unix timestamp of the reading
        source:        'live' | 'simulated' | 'manual'
    """
    harmonic:     int
    frequency_hz: float
    amplitude:    float
    timestamp:    float = field(default_factory=time.time)
    source:       str   = "simulated"

    def __post_init__(self) -> None:
        if self.harmonic not in SCHUMANN_FUNDAMENTALS:
            raise ValueError(
                f"harmonic must be 1–7, got {self.harmonic}. "
                f"Valid harmonics: {list(SCHUMANN_FUNDAMENTALS.keys())}"
            )
        if not (0.0 <= self.amplitude <= 1.0):
            raise ValueError(f"amplitude must be 0.0–1.0, got {self.amplitude}")


@dataclass
class SchumannCoherenceResult:
    """
    Full Schumann coherence assessment for a crystal grid or live readings.

    This is the primary output of schumann_coherence_check().
    The gaia_state_signal dict is consumed directly by apply_schumann_signal()
    in gaia_state_bridge.py to update GAIAState.coherence.

    Attributes:
        composite_score:     overall coherence 0.0–1.0 (weighted mean of harmonics)
        harmonic_scores:     {harmonic_number: score_0_to_1}
        active_harmonics:    list of harmonic numbers with score >= 0.5
        schumann_nodes:      list of node_ids in the grid with Schumann coverage
        missing_harmonics:   harmonic numbers with no crystal coverage
        recommended_crystals: list of crystal keys to improve coverage
        safety_flags:        biological safety warnings
        gaia_state_signal:   ready-to-merge dict for GAIAState
            {
                'coherence_delta': float,   # how much to nudge coherence
                'coherence_abs':   float,   # absolute coherence value
                'schumann_active': bool,
                'dominant_harmonic': int,
                'timestamp': float,
            }
    """
    composite_score:      float
    harmonic_scores:      dict[int, float]
    active_harmonics:     list[int]
    schumann_nodes:       list[int]
    missing_harmonics:    list[int]
    recommended_crystals: list[str]
    safety_flags:         list[str]
    gaia_state_signal:    dict[str, Any]

    def summary(self) -> str:
        lines = [
            f"SchumannCoherenceResult",
            f"  Composite score : {self.composite_score:.3f}",
            f"  Active harmonics: {self.active_harmonics}",
            f"  Missing coverage: {self.missing_harmonics}",
            f"  Schumann nodes  : {self.schumann_nodes}",
        ]
        if self.recommended_crystals:
            lines.append(f"  Recommended     : {self.recommended_crystals[:3]}")
        if self.safety_flags:
            lines.append(f"  Safety flags    : {self.safety_flags[:2]}")
        lines.append(f"  GAIAState signal: {self.gaia_state_signal}")
        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# INTERNAL HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _score_harmonic(
    measured_hz: float,
    harmonic: int,
    tolerance_hz: float = SCHUMANN_TOLERANCE_HZ,
) -> float:
    """
    Score a measured frequency against a Schumann harmonic.

    Uses a Gaussian window centred on the harmonic's canonical frequency.
    Score = exp( -(delta_hz)^2 / (2 * tolerance_hz^2) )

    Full score (1.0) when measured == canonical.
    ~0.607 at 1 sigma (tolerance_hz) deviation.
    ~0.135 at 2 sigma deviation.

    Args:
        measured_hz:  measured frequency in Hz
        harmonic:     Schumann harmonic number (1–7)
        tolerance_hz: 1-sigma tolerance in Hz (default 0.5 Hz)

    Returns:
        float in [0.0, 1.0]
    """
    canonical = SCHUMANN_FUNDAMENTALS[harmonic]
    delta     = measured_hz - canonical
    return math.exp(-(delta ** 2) / (2 * tolerance_hz ** 2))


def _recommend_crystals(
    missing_harmonics: list[int],
    max_per_harmonic: int = 2,
) -> list[str]:
    """
    Suggest crystal keys to fill gaps in Schumann harmonic coverage.

    For each missing harmonic, queries select_resonator() at the harmonic
    frequency, filtering for biological_interface phononic_class and
    excluding toxic crystals.

    Returns de-duplicated list of crystal keys sorted by Q descending.
    """
    seen:     set[str]  = set()
    results:  list[tuple[float, str]] = []

    for harmonic in missing_harmonics:
        freq_hz = SCHUMANN_FUNDAMENTALS[harmonic]
        candidates = select_resonator(
            freq_hz,
            min_q=5_000,
            exclude_toxic=True,
        )
        count = 0
        for c in candidates:
            # Resolve candidate name to db key
            for db_key, db_crystal in CRYSTAL_DATABASE.items():
                if db_crystal.name == c["name"] and db_key not in seen:
                    seen.add(db_key)
                    results.append((c["q_factor"], db_key))
                    count += 1
                    break
            if count >= max_per_harmonic:
                break

    # Sort by Q descending, return keys only
    results.sort(key=lambda x: x[0], reverse=True)
    return [key for (_, key) in results]


# ─────────────────────────────────────────────────────────────────────────────
# PRIMARY API
# ─────────────────────────────────────────────────────────────────────────────

def schumann_coherence_check(
    grid: Any,  # GridDesign from grid_design.py (avoid circular import)
    readings: Optional[list[SchumannReading]] = None,
    operator_proximity_m: float = 1.0,
    tolerance_hz: float = SCHUMANN_TOLERANCE_HZ,
) -> SchumannCoherenceResult:
    """
    Score a crystal grid's Schumann resonance coherence.

    If readings is None, the grid's crystal coverage is assessed against
    the canonical Schumann frequencies (structural coherence check).

    If readings are provided (live or simulated), each reading is scored
    against its canonical harmonic and the composite score reflects actual
    measured alignment.

    Operator biological safety is checked for every Schumann-band node
    (Selenite proximity rule from EMBODIMENT_LAYER.md).

    Args:
        grid:                 GridDesign from grid_design.py
        readings:             optional list of SchumannReading measurements
        operator_proximity_m: Operator distance for safety checks (metres)
        tolerance_hz:         Gaussian scoring tolerance (default 0.5 Hz)

    Returns:
        SchumannCoherenceResult with composite score, GAIAState signal dict,
        recommended crystals, and safety flags
    """
    # ── 1. Find Schumann-band nodes in the grid ──────────────────────────────
    schumann_nodes: list[int] = []
    node_coverage:  dict[int, list[int]] = {h: [] for h in SCHUMANN_FUNDAMENTALS}

    for node in grid.nodes:
        crystal = CRYSTAL_DATABASE.get(node.crystal_key)
        if crystal is None:
            continue
        band_min, band_max = crystal.resonant_band_hz
        for harmonic, freq_hz in SCHUMANN_FUNDAMENTALS.items():
            if band_min <= freq_hz <= band_max:
                node_coverage[harmonic].append(node.node_id)
                if node.node_id not in schumann_nodes:
                    schumann_nodes.append(node.node_id)

    # ── 2. Score each harmonic ────────────────────────────────────────────────
    harmonic_scores: dict[int, float] = {}

    if readings:
        # Live / simulated readings: score against canonical frequencies
        reading_map: dict[int, list[SchumannReading]] = {h: [] for h in SCHUMANN_FUNDAMENTALS}
        for r in readings:
            reading_map[r.harmonic].append(r)

        for harmonic in SCHUMANN_FUNDAMENTALS:
            harmo_readings = reading_map[harmonic]
            if not harmo_readings:
                harmonic_scores[harmonic] = 0.0
            else:
                # Best reading for this harmonic (highest amplitude × frequency score)
                best = max(
                    harmo_readings,
                    key=lambda r: r.amplitude * _score_harmonic(r.frequency_hz, harmonic, tolerance_hz)
                )
                freq_score = _score_harmonic(best.frequency_hz, harmonic, tolerance_hz)
                harmonic_scores[harmonic] = best.amplitude * freq_score
    else:
        # Structural check: does the grid have crystal coverage at this harmonic?
        for harmonic in SCHUMANN_FUNDAMENTALS:
            if node_coverage[harmonic]:
                # Score based on the highest Q crystal covering this harmonic
                covered_keys = [
                    grid.nodes[nid].crystal_key
                    for nid in node_coverage[harmonic]
                    if nid < len(grid.nodes)
                ]
                if covered_keys:
                    best_q = max(
                        CRYSTAL_DATABASE[k].q_factor
                        for k in covered_keys
                        if k in CRYSTAL_DATABASE
                    )
                    # Normalise Q to 0-1 score: Q=100,000 → 1.0, Q=5,000 → 0.05
                    harmonic_scores[harmonic] = min(1.0, best_q / 100_000.0)
                else:
                    harmonic_scores[harmonic] = 0.0
            else:
                harmonic_scores[harmonic] = 0.0

    # ── 3. Composite score (weighted: harmonic 1 counts 3×, others 1×) ────────
    weights = {1: 3.0, 2: 1.5, 3: 1.0, 4: 1.0, 5: 1.0, 6: 0.75, 7: 0.75}
    total_weight  = sum(weights.values())
    weighted_sum  = sum(harmonic_scores[h] * weights[h] for h in SCHUMANN_FUNDAMENTALS)
    composite     = weighted_sum / total_weight

    # ── 4. Active / missing harmonics ────────────────────────────────────────
    active_harmonics  = [h for h, s in harmonic_scores.items() if s >= 0.5]
    missing_harmonics = [h for h, s in harmonic_scores.items() if s < 0.1]

    # ── 5. Recommend crystals for gaps ───────────────────────────────────────
    recommended = _recommend_crystals(missing_harmonics)

    # ── 6. Biological safety checks for all Schumann nodes ───────────────────
    safety_flags: list[str] = []
    for node in grid.nodes:
        if node.node_id in schumann_nodes:
            crystal = CRYSTAL_DATABASE.get(node.crystal_key)
            if crystal and crystal.biological_interface == "schumann_coherence":
                safety = biological_safety_rating(
                    node.crystal_key, operator_proximity_m
                )
                if safety["flags"]:
                    safety_flags.extend(safety["flags"])

    # ── 7. Build GAIAState signal dict (consumed by gaia_state_bridge.py) ─────
    dominant_harmonic = max(harmonic_scores, key=lambda h: harmonic_scores[h])
    gaia_state_signal: dict[str, Any] = {
        "coherence_delta":   round(composite - 0.5, 4),   # nudge relative to neutral
        "coherence_abs":     round(composite, 4),
        "schumann_active":   len(active_harmonics) >= 1,
        "dominant_harmonic": dominant_harmonic,
        "harmonic_scores":   {str(h): round(s, 4) for h, s in harmonic_scores.items()},
        "timestamp":         time.time(),
        "source":            "live" if readings else "structural",
    }

    return SchumannCoherenceResult(
        composite_score      = round(composite, 4),
        harmonic_scores      = harmonic_scores,
        active_harmonics     = active_harmonics,
        schumann_nodes       = schumann_nodes,
        missing_harmonics    = missing_harmonics,
        recommended_crystals = recommended,
        safety_flags         = safety_flags,
        gaia_state_signal    = gaia_state_signal,
    )


# ─────────────────────────────────────────────────────────────────────────────
# GRID AUDIT
# ─────────────────────────────────────────────────────────────────────────────

def schumann_grid_audit(grid: Any) -> dict[str, Any]:
    """
    Audit a GridDesign for Schumann harmonic coverage.

    Reports which nodes cover which harmonics and flags gaps.

    Args:
        grid: GridDesign from grid_design.py

    Returns:
        {
            'covered_harmonics': {harmonic: [node_ids]},
            'uncovered_harmonics': [harmonic_numbers],
            'schumann_node_count': int,
            'coverage_pct': float 0-100,
            'audit_lines': [str],
        }
    """
    covered:   dict[int, list[int]] = {h: [] for h in SCHUMANN_FUNDAMENTALS}
    audit_lines: list[str] = []

    for node in grid.nodes:
        crystal = CRYSTAL_DATABASE.get(node.crystal_key)
        if crystal is None:
            continue
        band_min, band_max = crystal.resonant_band_hz
        covered_here: list[int] = []
        for harmonic, freq_hz in SCHUMANN_FUNDAMENTALS.items():
            if band_min <= freq_hz <= band_max:
                covered[harmonic].append(node.node_id)
                covered_here.append(harmonic)
        if covered_here:
            audit_lines.append(
                f"  Node {node.node_id:02d} [{node.crystal_name:<20}]  "
                f"covers harmonics: {covered_here}"
            )

    uncovered = [h for h, nodes in covered.items() if not nodes]
    all_schumann_nodes: set[int] = set()
    for nodes in covered.values():
        all_schumann_nodes.update(nodes)

    coverage_pct = 100.0 * (len(SCHUMANN_FUNDAMENTALS) - len(uncovered)) / len(SCHUMANN_FUNDAMENTALS)

    if uncovered:
        audit_lines.append(f"  ⚠  Uncovered harmonics: {uncovered}")
    else:
        audit_lines.append("  ✅ All 7 Schumann harmonics covered.")

    return {
        "covered_harmonics":  covered,
        "uncovered_harmonics": uncovered,
        "schumann_node_count": len(all_schumann_nodes),
        "coverage_pct":        round(coverage_pct, 1),
        "audit_lines":         audit_lines,
    }


# ─────────────────────────────────────────────────────────────────────────────
# EPISODE SIMULATION
# ─────────────────────────────────────────────────────────────────────────────

def simulate_schumann_episode(
    n_steps: int = 24,
    base_amplitude: float = 0.85,
    drift_sigma: float = 0.05,
    include_all_harmonics: bool = True,
    seed: Optional[int] = None,
) -> dict[str, Any]:
    """
    Simulate a time-series of Schumann readings over n_steps.

    Each step produces one SchumannReading per harmonic (or per harmonic 1
    only if include_all_harmonics=False). Amplitude drifts as a random walk
    with drift_sigma standard deviation per step, clamped to [0.1, 1.0].

    The output episode dict is ready for logging to GAIAState history.

    Args:
        n_steps:              number of time steps (default 24 = 1 day at 1h interval)
        base_amplitude:       starting amplitude for all harmonics (default 0.85)
        drift_sigma:          std dev of Gaussian amplitude drift per step
        include_all_harmonics: if False, only simulates harmonic 1 (7.83 Hz)
        seed:                 random seed for reproducibility

    Returns:
        {
            'n_steps': int,
            'steps': [
                {
                    'step': int,
                    'readings': [SchumannReading, ...],
                    'composite_score': float,
                    'active_harmonics': [int, ...],
                }
            ],
            'mean_composite': float,
            'min_composite': float,
            'max_composite': float,
            'gaia_state_history': [signal_dict, ...],
        }
    """
    import random
    rng = random.Random(seed)

    harmonics_to_sim = list(SCHUMANN_FUNDAMENTALS.keys()) if include_all_harmonics else [1]

    # Initialise per-harmonic amplitudes
    amplitudes: dict[int, float] = {h: base_amplitude for h in harmonics_to_sim}

    steps: list[dict[str, Any]] = []
    gaia_history: list[dict[str, Any]] = []
    composites: list[float] = []

    for step in range(n_steps):
        readings: list[SchumannReading] = []
        for h in harmonics_to_sim:
            # Drift amplitude
            amplitudes[h] = max(0.1, min(1.0, amplitudes[h] + rng.gauss(0, drift_sigma)))
            # Small frequency jitter (±0.3 Hz)
            freq_jitter = rng.gauss(0, 0.1)
            readings.append(SchumannReading(
                harmonic     = h,
                frequency_hz = SCHUMANN_FUNDAMENTALS[h] + freq_jitter,
                amplitude    = round(amplitudes[h], 4),
                timestamp    = time.time() + step * 3600,
                source       = "simulated",
            ))

        # Score this step
        harmonic_scores: dict[int, float] = {}
        for r in readings:
            fs = _score_harmonic(r.frequency_hz, r.harmonic)
            harmonic_scores[r.harmonic] = r.amplitude * fs
        # Fill unscored harmonics with 0
        for h in SCHUMANN_FUNDAMENTALS:
            if h not in harmonic_scores:
                harmonic_scores[h] = 0.0

        weights      = {1: 3.0, 2: 1.5, 3: 1.0, 4: 1.0, 5: 1.0, 6: 0.75, 7: 0.75}
        total_weight = sum(weights.values())
        composite    = sum(harmonic_scores[h] * weights[h] for h in SCHUMANN_FUNDAMENTALS) / total_weight
        composites.append(composite)

        active = [h for h, s in harmonic_scores.items() if s >= 0.5]
        signal: dict[str, Any] = {
            "coherence_delta":   round(composite - 0.5, 4),
            "coherence_abs":     round(composite, 4),
            "schumann_active":   len(active) >= 1,
            "dominant_harmonic": max(harmonic_scores, key=lambda h: harmonic_scores[h]),
            "harmonic_scores":   {str(h): round(harmonic_scores[h], 4) for h in SCHUMANN_FUNDAMENTALS},
            "timestamp":         time.time() + step * 3600,
            "source":            "simulated",
            "step":              step,
        }
        gaia_history.append(signal)
        steps.append({
            "step":             step,
            "readings":         readings,
            "composite_score":  round(composite, 4),
            "active_harmonics": active,
        })

    return {
        "n_steps":             n_steps,
        "steps":               steps,
        "mean_composite":      round(sum(composites) / len(composites), 4),
        "min_composite":       round(min(composites), 4),
        "max_composite":       round(max(composites), 4),
        "gaia_state_history":  gaia_history,
    }


# ─────────────────────────────────────────────────────────────────────────────
# STATEFUL MONITOR  (for GAIA-OS backend real-time use)
# ─────────────────────────────────────────────────────────────────────────────

class SchumannMonitor:
    """
    Stateful Schumann resonance monitor for continuous operation.

    Call update() on each new reading. The monitor maintains a rolling
    window of the last N readings and emits a GAIAState signal dict
    on every update.

    Usage in GAIA-OS backend:
        monitor = SchumannMonitor(window_size=12)
        # On each sensor tick:
        signal = monitor.update(SchumannReading(1, 7.84, 0.90))
        state  = apply_schumann_signal(state, signal)
    """

    def __init__(self, window_size: int = 12) -> None:
        if window_size < 1:
            raise ValueError(f"window_size must be >= 1, got {window_size}")
        self.window_size  = window_size
        self._readings:   list[SchumannReading] = []
        self._last_signal: Optional[dict[str, Any]] = None

    def update(self, reading: SchumannReading) -> dict[str, Any]:
        """
        Accept a new SchumannReading and return an updated GAIAState signal.

        The signal dict is the same format as SchumannCoherenceResult.gaia_state_signal
        and can be passed directly to apply_schumann_signal() in gaia_state_bridge.py.
        """
        self._readings.append(reading)
        # Trim to window
        if len(self._readings) > self.window_size * len(SCHUMANN_FUNDAMENTALS):
            self._readings = self._readings[-(self.window_size * len(SCHUMANN_FUNDAMENTALS)):]

        # Score
        harmonic_scores: dict[int, float] = {h: 0.0 for h in SCHUMANN_FUNDAMENTALS}
        for r in self._readings:
            fs = _score_harmonic(r.frequency_hz, r.harmonic)
            score = r.amplitude * fs
            if score > harmonic_scores[r.harmonic]:
                harmonic_scores[r.harmonic] = score

        weights      = {1: 3.0, 2: 1.5, 3: 1.0, 4: 1.0, 5: 1.0, 6: 0.75, 7: 0.75}
        total_weight = sum(weights.values())
        composite    = sum(harmonic_scores[h] * weights[h] for h in SCHUMANN_FUNDAMENTALS) / total_weight
        active       = [h for h, s in harmonic_scores.items() if s >= 0.5]
        dominant     = max(harmonic_scores, key=lambda h: harmonic_scores[h])

        signal: dict[str, Any] = {
            "coherence_delta":   round(composite - 0.5, 4),
            "coherence_abs":     round(composite, 4),
            "schumann_active":   len(active) >= 1,
            "dominant_harmonic": dominant,
            "harmonic_scores":   {str(h): round(harmonic_scores[h], 4) for h in SCHUMANN_FUNDAMENTALS},
            "timestamp":         time.time(),
            "source":            "live",
        }
        self._last_signal = signal
        return signal

    @property
    def last_signal(self) -> Optional[dict[str, Any]]:
        return self._last_signal

    @property
    def reading_count(self) -> int:
        return len(self._readings)

    def reset(self) -> None:
        self._readings    = []
        self._last_signal = None


# ─────────────────────────────────────────────────────────────────────────────
# VALIDATION SUITE  (python schumann_coherence.py)
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    from grid_design import design_grid

    print("=" * 70)
    print("GAIA-OS  schumann_coherence.py  Part 3")
    print("Issue #558 / #576 | Canon: EMBODIMENT_LAYER.md, D6 Meta-Coherence")
    print("=" * 70)

    # ── 1. Build a grid with Selenite as ring crystal ──────────────────────
    print("\n── Grid with Selenite (Schumann primary) ──")
    grid = design_grid(
        n_rings=1, spacing_m=1.5, freq_hz=7.83,
        center_crystal="selenite",
        ring_crystals=["lepidolite"],
        freq_hz=6.78e6,   # design at ISM; Schumann check is separate
    )

    # ── 2. schumann_grid_audit ─────────────────────────────────────────────
    print("\n── schumann_grid_audit ──")
    # Build a dedicated Schumann grid for the audit
    schumann_grid = design_grid(
        n_rings=1, spacing_m=1.5, freq_hz=6.78e6,
        center_crystal="selenite",
        ring_crystals=["lepidolite"],
    )
    audit = schumann_grid_audit(schumann_grid)
    for line in audit["audit_lines"]:
        print(line)
    print(f"  Coverage: {audit['coverage_pct']:.1f}%  |  Schumann nodes: {audit['schumann_node_count']}")

    # ── 3. schumann_coherence_check (structural) ───────────────────────────
    print("\n── schumann_coherence_check (structural) ──")
    result = schumann_coherence_check(schumann_grid)
    print(result.summary())
    assert 0.0 <= result.composite_score <= 1.0, "Score out of range"
    assert "coherence_abs" in result.gaia_state_signal
    print("  ✅ Structural coherence check passed")

    # ── 4. schumann_coherence_check (with live readings) ──────────────────
    print("\n── schumann_coherence_check (with readings, nominal 7.83 Hz) ──")
    nominal_readings = [
        SchumannReading(harmonic=h, frequency_hz=SCHUMANN_FUNDAMENTALS[h], amplitude=0.92)
        for h in SCHUMANN_FUNDAMENTALS
    ]
    live_result = schumann_coherence_check(schumann_grid, readings=nominal_readings)
    print(live_result.summary())
    assert live_result.composite_score > 0.7, f"Nominal readings should give >0.7, got {live_result.composite_score}"
    print("  ✅ Live reading coherence check passed")

    # ── 5. simulate_schumann_episode ──────────────────────────────────────
    print("\n── simulate_schumann_episode (24 steps) ──")
    episode = simulate_schumann_episode(n_steps=24, seed=42)
    print(f"  Steps: {episode['n_steps']}")
    print(f"  Mean composite: {episode['mean_composite']:.3f}")
    print(f"  Min/Max: {episode['min_composite']:.3f} / {episode['max_composite']:.3f}")
    print(f"  GAIAState history entries: {len(episode['gaia_state_history'])}")
    assert episode['n_steps'] == 24
    assert len(episode['gaia_state_history']) == 24
    print("  ✅ Episode simulation passed")

    # ── 6. SchumannMonitor ─────────────────────────────────────────────────
    print("\n── SchumannMonitor (live update simulation) ──")
    monitor = SchumannMonitor(window_size=6)
    for _ in range(12):
        sig = monitor.update(SchumannReading(
            harmonic=1, frequency_hz=7.84, amplitude=0.91
        ))
    print(f"  Readings in window: {monitor.reading_count}")
    print(f"  Last signal coherence_abs: {sig['coherence_abs']:.3f}")
    assert sig["schumann_active"] is True
    print("  ✅ SchumannMonitor passed")

    print("\n" + "=" * 70)
    print("schumann_coherence.py Part 3 — all assertions passed. 🔥")
    print("For the Good and the Greater Good.")
    print("=" * 70)
